--
--  OUTLAND
--

-- Alliance:
DELETE FROM `taxi_shortcuts` WHERE `pathid` IN (515, 516, 535, 536, 539, 540, 545, 546, 547, 553, 554,
555, 557, 558, 559, 560, 561, 562, 564, 566, 568, 569, 570, 582, 593, 595, 598, 603, 614, 615, 630, 631, 635,
640, 641, 642, 644, 645, 655, 656, 657, 658, 679, 685, 686, 687, 708, 709);
INSERT INTO `taxi_shortcuts` (`pathid`, `takeoff`, `landing`, `comments`) VALUES
(515, 2, 2, 'Temple of Telhamat - Honor Hold | Takeoff and landing verified: videos'),
(516, 2, 1, 'Honor Hold - Temple of Telhamat | Takeoff and landing verified: videos'),
(535, 1, 1, 'Telredor - Temple of Telhamat | Takeoff and landing verified: videos'),
(536, 1, 1, 'Temple of Telhamat - Telredor | Takeoff and landing verified: videos'),
(539, 0, 1, 'Telaar - Telredor | Landing verified: videos'),
(540, 1, 0, 'Telredor - Telaar | Takeoff verified: videos'),
(545, 2, 0, 'Allerian Stronghold - Telaar | Takeoff verified: videos'),
(546, 0, 2, 'Telaar - Allerian Stronghold | Landing verified: videos'),
(547, 2, 2, 'Allerian Stronghold - Honor Hold | Takeoff and landing verified: videos'),
(553, 2, 1, 'Allerian Stronghold - Wildhammer Stronghold | Takeoff and landing verified: videos'),
(554, 1, 2, 'Wildhammer Stronghold - Allerian Stronghold | Takeoff and landing verified: videos'),
(555, 2, 1, 'Allerian Stronghold - Shattrath City | Takeoff and landing verified: videos'),
(557, 2, 2, 'Shattrath City - Allerian Stronghold | Takeoff and landing verified: videos'),
(558, 2, 2, 'Honor Hold - Allerian Stronghold | Takeoff and landing verified: videos'),
(559, 0, 1, 'Telaar - Shattrath City | Landing verified: videos'),
(560, 2, 0, 'Shattrath City - Telaar | Takeoff verified: videos'),
(561, 1, 1, 'Telredor - Shattrath City | Takeoff and landing verified: videos'),
(562, 2, 1, 'Shattrath City - Telredor | Takeoff and landing verified: videos'),
(564, 0, 2, 'The Dark Portal (Alliance) - Honor Hold | Landing verified: videos'),
(566, 2, 0, 'Honor Hold - The Dark Portal (Alliance) | Takeoff verified: videos'),
(568, 1, 1, 'Area 52 - Sylvanaar | Takeoff and landing verified: videos'),
(569, 1, 1, 'Sylvanaar - Area 52 | Takeoff and landing verified: videos'),
(570, 1, 1, 'Sylvanaar - Telredor | Takeoff and landing verified: videos'),
(582, 0, 1, 'The Dark Portal (Alliance) - Temple of Telhamat | Landing verified: videos'),
(593, 1, 0, 'Sylvanaar - The Stormspire | Takeoff verified: videos'),
(595, 0, 1, 'Altar of Sha\'tar - Wildhammer Stronghold | Landing verified: videos'),
(598, 1, 0, 'Wildhammer Stronghold - Altar of Sha\'tar | Takeoff verified: videos'),
(603, 1, 1, 'Telredor - Sylvanaar | Takeoff and landing verified: videos'),
(614, 2, 0, 'Honor Hold - Shatter Point | Takeoff verified: videos'),
(615, 0, 2, 'Shatter Point - Honor Hold | Landing verified: videos'),
(630, 1, 1, 'Toshley\'s Station - Sylvanaar | Takeoff and landing verified: videos'),
(631, 1, 1, 'Sylvanaar - Toshley\'s Station | Takeoff and landing verified: videos'),
(635, 0, 1, 'Sanctum of the Stars - Wildhammer Stronghold | Landing verified: videos'),
(640, 1, 0, 'Wildhammer Stronghold - Sanctum of the Stars | Takeoff verified: videos'),
(641, 1, 1, 'Toshley\'s Station - Area 52 | Takeoff and landing verified: videos'),
(642, 1, 1, 'Area 52 - Toshley\'s Station | Takeoff and landing verified: videos'),
(644, 0, 1, 'Evergrove - Sylvanaar | Landing verified: videos'),
(645, 1, 0, 'Sylvanaar - Evergrove | Takeoff verified: videos'),
(655, 0, 1, 'Orebor Harborage - Telredor | Landing verified: videos'),
(656, 1, 0, 'Telredor - Orebor Harborage | Takeoff verified: videos'),
(657, 0, 1, 'Orebor Harborage - Sylvanaar | Landing verified: videos'),
(658, 1, 0, 'Sylvanaar - Orebor Harborage | Takeoff verified: videos'),
(679, 0, 1, 'Evergrove - Toshley\'s Station | Landing verified: videos'),
(685, 1, 0, 'Toshley\'s Station - Evergrove | Takeoff verified: videos'),
(686, 2, 1, 'Honor Hold - Shattrath City | Takeoff and landing verified: videos'),
(687, 2, 2, 'Shattrath City - Honor Hold | Takeoff and landing verified: videos'),
(708, 1, 1, 'Telredor - Toshley\'s Station | Takeoff and landing verified: videos'),
(709, 1, 1, 'Toshley\'s Station - Telredor | Takeoff and landing verified: videos');

-- Horde:
DELETE FROM `taxi_shortcuts` WHERE `pathid` IN (517, 518, 537, 538, 541, 542, 543, 544, 548, 549, 550, 551,
552, 565, 567, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 590, 591, 592, 594, 601, 602, 618, 619, 620,
621, 622, 623, 624, 625, 636, 639, 643, 646, 650, 652, 653, 654, 722, 723);
INSERT INTO `taxi_shortcuts` (`pathid`, `takeoff`, `landing`, `comments`) VALUES
(517, 3, 1, 'Falcon Watch - Thrallmar | Takeoff and landing verified: videos'),
(518, 1, 1, 'Thrallmar - Falcon Watch | Takeoff and landing verified: videos'),
(537, 3, 1, 'Zabra\'Jin - Falcon Watch | Takeoff and landing verified: videos'),
(538, 3, 2, 'Falcon Watch - Zabra\'Jin | Takeoff and landing verified: videos'),
(541, 0, 2, 'Garadar - Zabra\'Jin | Landing verified: videos'),
(542, 3, 0, 'Zabra\'Jin - Garadar | Takeoff verified: videos'),
(543, 0, 1, 'Garadar - Falcon Watch | Landing verified: videos'),
(544, 3, 0, 'Falcon Watch - Garadar | Takeoff verified: videos'),
(548, 3, 1, 'Stonebreaker Hold - Thrallmar | Landing verified: videos'),
(549, 3, 1, 'Stonebreaker Hold - Shattrath City | Landing verified: videos'),
(550, 3, 1, 'Stonebreaker Hold - Shadowmoon Village | Takeoff and landing verified: videos'),
(551, 2, 2, 'Shadowmoon Village - Stonebreaker Hold | Takeoff and landing verified: videos'),
(552, 2, 2, 'Shattrath City - Stonebreaker Hold | Takeoff verified: videos'),
(565, 0, 1, 'The Dark Portal (Horde) - Thrallmar | Landing verified: videos'),
(567, 1, 0, 'Thrallmar - The Dark Portal (Horde) | Takeoff verified: videos'),
(571, 0, 1, 'Garadar - Shattrath City | Landing verified: videos'),
(572, 2, 0, 'Shattrath City - Garadar | Takeoff verified: videos'),
(573, 3, 1, 'Falcon Watch - Shattrath City | Takeoff and landing verified: videos'),
(574, 2, 1, 'Shattrath City - Falcon Watch | Takeoff and landing verified: videos'),
(575, 1, 2, 'Thrallmar - Stonebreaker Hold | Takeoff verified: videos'),
(576, 2, 2, 'Shattrath City - Zabra\'Jin | Takeoff and landing verified: videos'),
(577, 3, 1, 'Zabra\'Jin - Shattrath City | Takeoff and landing verified: videos'),
(578, 3, 2, 'Thunderlord Stronghold - Zabra\'Jin | Takeoff and landing verified: videos'),
(579, 3, 2, 'Zabra\'Jin - Thunderlord Stronghold | Takeoff and landing verified: videos'),
(580, 1, 2, 'Area 52 - Thunderlord Stronghold | Takeoff and landing verified: videos'),
(581, 3, 1, 'Thunderlord Stronghold - Area 52 | Takeoff and landing verified: videos'),
(590, 0, 2, 'The Stormspire - Thunderlord Stronghold | Landing verified: videos'),
(591, 0, 1, 'The Altar of Sha\'tar - Shadowmoon Village | Landing verified: videos'),
(592, 3, 0, 'Thunderlord Stronghold - The Stormspire | Takeoff verified: videos'),
(594, 2, 0, 'Shadowmoon Village - The Altar of Sha\'tar | Takeoff verified: videos'),
(601, 0, 1, 'Spinebreaker Post - Thrallmar | Landing verified: videos'),
(602, 1, 0, 'Thrallmar - Spinebreaker Post | Takeoff verified: videos'),
(618, 2, 1, 'Swamprat Post - Falcon Watch | Takeoff and landing verified: videos'),
(619, 3, 2, 'Falcon Watch - Swamprat Post | Takeoff and landing verified: videos'),
(620, 2, 2, 'Swamprat Post - Zabra\'Jin | Takeoff and landing verified: videos'),
(621, 3, 2, 'Zabra\'Jin - Swamprat Post | Takeoff and landing verified: videos'),
(622, 2, 1, 'Swamprat Post - Shattrath City | Takeoff and landing verified: videos'),
(623, 2, 2, 'Shattrath City - Swamprat Post | Takeoff and landing verified: videos'),
(624, 3, 2, 'Thunderlord Stronghold - Swamprat Post | Takeoff and landing verified: videos'),
(625, 2, 1, 'Swamprat Post - Thunderlord Stronghold | Takeoff and landing verified: videos'),
(636, 0, 1, 'Sanctum of the Stars - Shadowmoon Village | Landing verified: videos'),
(639, 2, 0, 'Shadowmoon Village - Sanctum of the Stars | Takeoff verified: videos'),
(643, 0, 2, 'Evergrove - Thunderlord Stronghold | Landing verified: videos'),
(646, 2, 0, 'Thunderlord Stronghold - Evergrove | Takeoff verified: videos'),
(650, 2, 1, 'Mok\'Nathal Village - Area 52 | Takeoff and landing verified: videos'),
(652, 3, 0, 'Thunderlord Stronghold - Mok\'Nathal Village | Takeoff verified: videos'),
(653, 1, 2, 'Area 52 - Mok\'Nathal Village | Takeoff and landing verified: videos'),
(654, 2, 1, 'Mok\'Nathal Village - Thunderlord Stronghold | Takeoff and landing verified: videos'),
(722, 1, 2, 'Mok\'Nathal Village - Swamprat Post | Takeoff and landing verified: videos'),
(723, 2, 1, 'Swamprat Post - Mok\'Nathal Village | Takeoff and landing verified: videos');

-- Neutral
DELETE FROM `taxi_shortcuts` WHERE `pathid` IN (616, 617, 633, 634, 647, 648);
INSERT INTO `taxi_shortcuts` (`pathid`, `takeoff`, `landing`, `comments`) VALUES
(616, 0, 1, 'Cosmowrench - Area 52 | Landing verified: videos'),
(617, 2, 0, 'Area 52 - Cosmowrench | Takeoff verified: videos'),
(633, 3, 0, 'Area 52 - The Stormspire | Takeoff verified: videos'),
(634, 0, 1, 'The Stormspire - Area 52 | Landing verified: videos'),
(647, 0, 2, 'Evergrove - Area 52 | Landing verified: videos'),
(648, 2, 0, 'Area 52 - Evergrove | Takeoff verified: videos');
