UPDATE dbscript_string SET content_default="Let us return to the grove, mortal.", broadcast_text_id=10879 WHERE entry=2000000387;
UPDATE dbscript_string SET content_default="Farewell, old friend... Farewell...", broadcast_text_id=10877 WHERE entry=2000000386;
UPDATE dbscript_string SET content_default="I sensed as much, Malfurion. Dark days loom ahead.", broadcast_text_id=10872 WHERE entry=2000000381;
UPDATE dbscript_string SET content_default="It was shrouded in nightmares, Malfurion. What is happening in the Dream? What could cause such atrocities?", broadcast_text_id=10870 WHERE entry=2000000379;
UPDATE dbscript_string SET content_default="Stand near me, $N. I will protect you should anything go wrong.", broadcast_text_id=10867 WHERE entry=2000000376;
UPDATE dbscript_string SET content_default=" I am going to practice and become a warrior like my father!", broadcast_text_id=10293 WHERE entry=2000005767;
UPDATE dbscript_string SET content_default="Come one, come all!  Welcome to the Darkmoon Faire!  Do you crave adventure?  Do you seek exotic and mysterious treasures?  Then look no further!  You, my friend, have come to the right place!  Dive right in and take part in all that the Faire has to offer!  We'll be at this location all week, so be sure to tell your friends and loved ones!", broadcast_text_id=10158 WHERE entry=2000005033;
UPDATE dbscript_string SET content_default="Greetings friends, and welcome to the greatest show on Azeroth!$B$BPlease, step right up and take in all we have to offer.  Ride the rides and see the sights!  Amaze at the wonders that the Darkmoon Faire has uncovered in this vast and mysterious world!  We have spared no expense in bringing you excitement that children of all ages will delight in!", broadcast_text_id=10157 WHERE entry=2000005217;
UPDATE dbscript_string SET content_default="Prizes!  Get your prizes right here!  Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!", broadcast_text_id=10152 WHERE entry=2000005025;
UPDATE dbscript_string SET content_default="Tickets! Redeem your Darkmoon Faire Prize Tickets here!  Wondrous and exotic prizes are waiting for you!", broadcast_text_id=10149 WHERE entry=2000005212;
UPDATE dbscript_string SET content_default="Fear not!  All fortunes can be discerned for those who know the way.", broadcast_text_id=10127 WHERE entry=2000005213;
UPDATE dbscript_string SET content_default="Well, that should do it.  Come now, back to the shop to finish our business!", broadcast_text_id=9779 WHERE entry=2000000064;
UPDATE dbscript_string SET content_default="Arrr, Me Hearties!   I be havin' some extra Treasure that I be givin' away at the Gurubashi Arena!  All ye need do to collect it is open the chest I leave on the arena floor!", broadcast_text_id=9730 WHERE entry=2000009077;
UPDATE dbscript_string SET content_default="I will need to focus my energies onto this knife.  By doing so, I should catch some of the stronger psychic impressions associated with it.", broadcast_text_id=5148 WHERE entry=2000000521;
UPDATE dbscript_string SET content_default="Oh man, I thought I was dead for sure.  Ugh... still dizzy...", broadcast_text_id=4949 WHERE entry=2000000519;
UPDATE dbscript_string SET content_default="Oooooo hot hot hot!  If that won't put spring in your step, I don't know what will!", broadcast_text_id=4378 WHERE entry=2000000046;
UPDATE dbscript_string SET content_default="Greetings, mortals!  I have been activated by the Discs of Norgannon to assist you!", broadcast_text_id=3308 WHERE entry=2000000823;
UPDATE dbscript_string SET content_default="Follow, $N.  I will soon begin the summoning...", broadcast_text_id=2383 WHERE entry=2000005522;
UPDATE dbscript_string SET content_default="Ugh!  That's terrible!", broadcast_text_id=2079 WHERE entry=2000005753;
UPDATE dbscript_string SET content_default="When time permits, we must speak at length.  For we have much to discuss.", broadcast_text_id=1974 WHERE entry=2000000209;
UPDATE dbscript_string SET content_default="Hey $N!  Don't forget to grab a crate, a manual and a command stick!", broadcast_text_id=1788 WHERE entry=2000000107;
UPDATE dbscript_string SET content_default="Wow!  $N, that dream dust is powerful stuff!", broadcast_text_id=1551 WHERE entry=2000000129;
UPDATE dbscript_string SET content_default="Hahah!  $N, you make quite a partner!", broadcast_text_id=1481 WHERE entry=2000005084;
UPDATE dbscript_string SET content_default="There we are, $N.  The toxin is ready.", broadcast_text_id=1422 WHERE entry=2000000111;
UPDATE dbscript_string SET content_default="Thank you again, $N.  This rare earth will be very helpful in my experiments.", broadcast_text_id=1240 WHERE entry=2000000049;
UPDATE dbscript_string SET content_default="Thank you, $N.  And luck to you.", broadcast_text_id=1211 WHERE entry=2000009045;
UPDATE dbscript_string SET content_default="I have created the totem.  You, $N, must cleanse the well.", broadcast_text_id=1009 WHERE entry=2000000171;
UPDATE dbscript_string SET content_default="The totem is made.  The well may now be cleansed.", broadcast_text_id=1006 WHERE entry=2000000175;
UPDATE dbscript_string SET content_default="I thank you, $N.  And my brother thanks you.", broadcast_text_id=983 WHERE entry=2000005776;
UPDATE dbscript_string SET content_default="What??  The Burning Blade is spreading!  We must investigate!", broadcast_text_id=982 WHERE entry=2000005778;
UPDATE dbscript_string SET content_default="Bah!  $N, this foot won't budge!", broadcast_text_id=745 WHERE entry=2000009025;
UPDATE dbscript_string SET content_default="The Stonewrought Dam has been saved!  Three cheers for $N!", broadcast_text_id=546 WHERE entry=2000009019;
UPDATE dbscript_string SET content_default="I. . .I. . .don't. . .feel. . .right. . .", broadcast_text_id=425 WHERE entry=2000009022;
UPDATE dbscript_string SET content_default="I feel... dizzy.  It's so hot... in... here...", broadcast_text_id=388 WHERE entry=2000009021;
UPDATE dbscript_string SET content_default="Hullo, Trias clan!  A ball of your smoked mozzarella, if you please!", broadcast_text_id=285 WHERE entry=2000000152;
UPDATE dbscript_string SET content_default="Beware!  Beware!  A threat lurks in the wild!  Night Watchers, be on the alert!", broadcast_text_id=276 WHERE entry=2000000244;
UPDATE dbscript_string SET content_default="Ah yes, and promptly delivered.  As always, it's a pleasure doing business with you, Corbett.", broadcast_text_id=262 WHERE entry=2000000147;
UPDATE dbscript_string SET content_default="I should have a few extra coins from this sale.  Maybe I'll buy myself some lunch...", broadcast_text_id=258 WHERE entry=2000000144;
UPDATE dbscript_string SET content_default="Business must be good down at the bazaar.  I'll get him resupplied right away!", broadcast_text_id=256 WHERE entry=2000000142;
UPDATE dbscript_string SET content_default="My pleasure, sugar drop.  I'll be back soon...", broadcast_text_id=255 WHERE entry=2000000141;
UPDATE dbscript_string SET content_default="Well, back to business for me.  But it sure was nice taking that short break, and it's always nice drinking Thunder Ale!", broadcast_text_id=128 WHERE entry=2000000079;
UPDATE dbscript_string SET content_default="Ah, that sure does hit the spot!  I think I'll get myself a couple more...can you watch these barrels for me, $N?", broadcast_text_id=127 WHERE entry=2000000077;
UPDATE dbscript_string SET content_default="Hey there, Belm!  Give me a mug of Thunder Ale, and one for my good friend $N.", broadcast_text_id=125 WHERE entry=2000000056;
UPDATE dbscript_string SET content_default="Time for my patrol.  I'll be back shortly.", broadcast_text_id=102 WHERE entry=2000009105;
UPDATE dbscript_string SET content_default="The boss wants all hands on high alert.  The rusty anchor sinks tonight.", broadcast_text_id=37 WHERE entry=2000005408;
UPDATE dbscript_string SET content_default="Stonemasons. . .errr. . Defias be warned:  The rusty anchor sinks tonight.", broadcast_text_id=36 WHERE entry=2000005407;
UPDATE dbscript_string SET content_default="Blasted scrying crystal!  I'm not getting anything over here.", broadcast_text_id=14902 WHERE entry=2000000803;
UPDATE dbscript_string SET content_default="S-sir... have you tried giving the crystal a good shake?  It's possible that the ley-lines are clouding up the reading.", broadcast_text_id=15053 WHERE entry=2000000804;
UPDATE dbscript_string SET content_default="I ought to give your head a good shake!  I've a feeling the ley-lines are clouding up your brain.  No, Darius, what we need is a large depository of mineral-heavy water.  Even faint arcane signals will accumulate in sulphur and lime.", broadcast_text_id=15054 WHERE entry=2000000800;
UPDATE dbscript_string SET content_default="Thank you all for coming tonight.  Now put your hands together to welcome Shattrath's best, Perry Gatner!", broadcast_text_id=16383 WHERE entry=2000005300;
UPDATE dbscript_string SET content_default="Perry Gatner! What an act!  The cantina is open all night long, so please, stay and enjoy yourselves!", broadcast_text_id=16384 WHERE entry=2000005301;
UPDATE dbscript_string SET content_default="Sir!  If I don't get out there and fight for Azeroth, then why am I in this army? I enlisted to do a job, and I intend to see it through.", broadcast_text_id=16715 WHERE entry=2000001417;
UPDATE dbscript_string SET content_default="NEVER AGAIN!! Next time some wounded soldier wants to return to the front line, I am putting my foot down.  I mean it this time.", broadcast_text_id=16739 WHERE entry=2000001414;
UPDATE dbscript_string SET content_default="Look, sweetheart.  No one's talking about storming Tempest Keep ourselves, but when we see a target of opportunity we have to take it.", broadcast_text_id=16872 WHERE entry=2000005272;
UPDATE dbscript_string SET content_default="Hold your tongue, knave!  Do not dare use that tone with a priestess of the Light!", broadcast_text_id=16873 WHERE entry=2000005273;
UPDATE dbscript_string SET content_default="Even you must admit that your information from defectors is outdated and unreliable.  Let us make calculated attacks on these manaforges and gather what information we can.", broadcast_text_id=16890 WHERE entry=2000005279;
UPDATE dbscript_string SET content_default="If this is right, we don't have long!  Oh well.", broadcast_text_id=16953 WHERE entry=2000005066;
UPDATE dbscript_string SET content_default="If I were smart, I'd be selling this research for a seat on the rocket ship.  I have a feeling we're going to need to get out of here soon!", broadcast_text_id=16955 WHERE entry=2000005065;
UPDATE dbscript_string SET content_default="This wanted poster says that they're offering gold to these so-called adventurers to go kill things.  Isn't that what we do?  I don't think I'm being paid enough!", broadcast_text_id=16970 WHERE entry=2000005684;
UPDATE dbscript_string SET content_default="The bonelashers of the wastes are no laughing matter.  I hear they carry diseases!", broadcast_text_id=16978 WHERE entry=2000005688;
UPDATE dbscript_string SET content_default="Hmm... the readings on the gravimeteric distortions seem to have stabalized.  We did it!", broadcast_text_id=17020 WHERE entry=2000005260;
UPDATE dbscript_string SET content_default="According to these readings, we have nothing to fear.  At least nothing in the near future.  We'll need more data to be sure.", broadcast_text_id=17059 WHERE entry=2000005262;
UPDATE dbscript_string SET content_default="Hail, Gezhe!  Seventeen more orders have been placed in the Hara'samid Sector.  The markets of heavy veldarite have all but collapsed, as you predicted.", broadcast_text_id=17184 WHERE entry=2000005362;
UPDATE dbscript_string SET content_default="Heraazi exports are on the rise, sir.  We've already bribed the appropriate taxation officers and contraband will begin to arrive within days.", broadcast_text_id=17186 WHERE entry=2000005363;
UPDATE dbscript_string SET content_default="As expected.  Very well, dismissed.", broadcast_text_id=17190 WHERE entry=2000005365;
UPDATE dbscript_string SET content_default="Nothing surprising there.  Come back with some real news, will you?", broadcast_text_id=17191 WHERE entry=2000005364;
UPDATE dbscript_string SET content_default="What manner of creature is that?  Looks like a purple goblin.", broadcast_text_id=17237 WHERE entry=2000005591;
UPDATE dbscript_string SET content_default="Do not burden A'dal with mundane questions, $r.  This being's will is all that keeps our enemies from crushing this city.", broadcast_text_id=17238 WHERE entry=2000000221;
UPDATE dbscript_string SET content_default="Brutish though they seem, these iron-stitched horrors are exceedingly brilliant engineers and forge-smiths.", broadcast_text_id=17405 WHERE entry=2000000741;
UPDATE dbscript_string SET content_default="The ship's not ready yet.  We still need to calibrate the fuse length to make sure that it doesn't burn out and leave you up there alone.", broadcast_text_id=17414 WHERE entry=2000005249;
UPDATE dbscript_string SET content_default="Essentially, it's going to be a long, long time till we are ready to launch.  Maybe you should just head back home to your family.", broadcast_text_id=17417 WHERE entry=2000005251;
UPDATE dbscript_string SET content_default="I can't. I'm not the man they think I am at home.  Besides, I didn't bring them out here.", broadcast_text_id=17419 WHERE entry=2000005252;
UPDATE dbscript_string SET content_default="Well, it's like I said; it's going to be a while before we get this ship ready for flight.  We'll keep you informed.", broadcast_text_id=17424 WHERE entry=2000005257;
UPDATE dbscript_string SET content_default="Hey, you there.  Want some candy?", broadcast_text_id=17486 WHERE entry=2000005052;
UPDATE dbscript_string SET content_default="What up son!  Wait....is anyone there?", broadcast_text_id=17488 WHERE entry=2000005055;
UPDATE dbscript_string SET content_default="If you think I'll betray my friend that easily, think again!  Face me, you scoundrel!", broadcast_text_id=17758 WHERE entry=2000000253;
UPDATE dbscript_string SET content_default="Speak with Wing Commander Brack, $n.  He'll outfit you with one of our armored wyvern destroyers.  And, good luck!", broadcast_text_id=17964 WHERE entry=2000000180;
UPDATE dbscript_string SET content_default="I thought this was going to be our chance to get away from it all?  Our vacation?", broadcast_text_id=18817 WHERE entry=2000005680;
UPDATE dbscript_string SET content_default="ACK!  That's the worst thing I've ever tasted!  I wouldn't let my ram drink that!", broadcast_text_id=18830 WHERE entry=2000000284;
UPDATE dbscript_string SET content_default="Hah!  The Thunderspike is mine.  Die!", broadcast_text_id=18979 WHERE entry=2000001123;
UPDATE dbscript_string SET content_default="Puny $r cannot lift spear.  Gor lift spear!", broadcast_text_id=18980 WHERE entry=2000001122;
UPDATE dbscript_string SET content_default="Keep up the good work.  Do well and you will be rewarded by the master.", broadcast_text_id=19153 WHERE entry=2000005470;
UPDATE dbscript_string SET content_default=" I think that we should teach a lesson to both the Horde and the Alliance.  One that they will not soon forget!", broadcast_text_id=19194 WHERE entry=2000001326;
UPDATE dbscript_string SET content_default="Our ally has arrived!  Clear the way to the materialization chamber!", broadcast_text_id=19417 WHERE entry=2000007706;
UPDATE dbscript_string SET content_default="Now, proceed to the translocator.  Forge Camp Wrath awaits your arrival!", broadcast_text_id=19418 WHERE entry=2000007707;
UPDATE dbscript_string SET content_default="Mine rock!  Crack stone!  Faster!  Faster!", broadcast_text_id=19593 WHERE entry=2000001442;
UPDATE dbscript_string SET content_default="The Heart of Fury... I witnessed its power long ago, when Velen wielded it.  I feel the same power coursing through it right now!", broadcast_text_id=19858 WHERE entry=2000001003;
UPDATE dbscript_string SET content_default="With this crystal's powers, my Deathsworn and I... we'd be unstoppable!  We could destroy Illidan!  We could... replace him as lords of Outland!", broadcast_text_id=19859 WHERE entry=2000001004;
UPDATE dbscript_string SET content_default="Yay!  We're free!", broadcast_text_id=20109 WHERE entry=2000001363;
UPDATE dbscript_string SET content_default="Your name is as insignificant to me as the names of the thousands who have died under the might of Goc.  I will crush you and $n!", broadcast_text_id=20321 WHERE entry=2000005901;
UPDATE dbscript_string SET content_default="Slay all who see us!  Word must not get back to Illidan.", broadcast_text_id=20744 WHERE entry=2000005528;
UPDATE dbscript_string SET content_default="Our plans are in danger already.  It appears Maiev's decided to do things her own way.", broadcast_text_id=20748 WHERE entry=2000005533;
UPDATE dbscript_string SET content_default="We must carry on with or without Maiev.  Inside!  Quickly!", broadcast_text_id=20750 WHERE entry=2000005535;
UPDATE dbscript_string SET content_default="Rest now, Adaris.  You need to recover your strength.", broadcast_text_id=21918 WHERE entry=2000009050;
UPDATE dbscript_string SET content_default="Greetings friends, and welcome to the greatest show on Azeroth!$B$BPlease, step right up and take in all we have to offer.  Ride the rides and see the sights!  Amaze at the wonders that the Darkmoon Faire has uncovered in this vast and mysterious world!  We have spared no expense in bringing you excitement that children of all ages will delight in!", broadcast_text_id=22542 WHERE entry=2000005217;
UPDATE dbscript_string SET content_default="Everyone enjoying themselves so far?  That's great!  Welcome to the Darkmoon Faire, the greatest show in all of Outland!  Make sure that you speak with Yebb and his friends here while you're taking in Neblegear's Darkmoon Zoo Bizarre.", broadcast_text_id=22543 WHERE entry=2000005216;
UPDATE dbscript_string SET content_default="Avruu's magic... it still controls me.  You must fight me, mortal.  It's the only way to break the spell!", broadcast_text_id=13448 WHERE entry=2000005654;
UPDATE dbscript_string SET content_default="Thrall!  My lord... are you all right?", broadcast_text_id=13542 WHERE entry=2000000098;
UPDATE dbscript_string SET content_default="At once, sir!  For the Horde!", broadcast_text_id=13544 WHERE entry=2000000102;
UPDATE dbscript_string SET content_default="Drink this, you blue brute!  Disobey me and I promise you a slow, painful death!", broadcast_text_id=13683 WHERE entry=2000000256;
UPDATE dbscript_string SET content_default="[Furbolg] Bear witness to the savage acts of our adversaries, $n. They steal our young... our weak... Imprisoned here, they are left to the devices of the Bristlelimb. Set them free, Promised One!", broadcast_text_id=13950 WHERE entry=2000000679;
UPDATE dbscript_string SET content_default="The wind speaks of our enemies' movements, Ashyen.  The naga will attack again.", broadcast_text_id=14565 WHERE entry=2000005039;
UPDATE dbscript_string SET content_default="Very well.  When that decision is made, I will be ready.  Let us hope it won't be too late.", broadcast_text_id=14567 WHERE entry=2000005040;
UPDATE dbscript_string SET content_default="We'd do well not to be reckless.  There's still much to learn about this land and about the enemy.", broadcast_text_id=14568 WHERE entry=2000005245;
UPDATE dbscript_string SET content_default="We will act when we know what we need, old friend.  The druids have proven wise and capable of making their own decisions.", broadcast_text_id=14569 WHERE entry=2000005247;
UPDATE dbscript_string SET content_default="The Wickerman Festival now begins!  Power to the Forsaken!", broadcast_text_id=10861 WHERE entry=2000001021;
UPDATE dbscript_string SET content_default="The burning of the Wickerman will begin in five minutes!  Come to the festival - located just west of the Undercity - and celebrate Hallow's End and our liberation from the Scourge!", broadcast_text_id=10860 WHERE entry=2000001020;
UPDATE dbscript_string SET content_default="The burning of the Wickerman will begin in fifteen minutes!  Come to the festival - located just west of the Undercity - and celebrate Hallow's End and our liberation from the Scourge!", broadcast_text_id=10859 WHERE entry=2000001019;
UPDATE dbscript_string SET content_default="The burning of the Wickerman will begin in thirty minutes!  Come to the festival - located just west of the Undercity - and celebrate Hallow's End and our liberation from the Scourge!", broadcast_text_id=10856 WHERE entry=2000001018;
UPDATE dbscript_string SET content_default="NOW is the time of the Forsaken!  Power to the Forsaken - NOW AND FOREVER!!!", broadcast_text_id=10667 WHERE entry=2000001017;
UPDATE dbscript_string SET content_default="We burn the effigy of the Wickerman as a symbol of our struggle against those who would oppose us.  We wear the ashes of the burnt Wickerman as a symbol of our neverending fight against those who would enslave us.", broadcast_text_id=10666 WHERE entry=2000001015;
UPDATE dbscript_string SET content_default="Now is the time to shake the world to its foundations!  NOW is the time to remind those who would enslave us that we shall never yield!", broadcast_text_id=10665 WHERE entry=2000001016;
UPDATE dbscript_string SET content_default="It is this night that our enemies fear us the most.  It is THIS night that we show our enemies what it means to stand against the Forsaken!", broadcast_text_id=10664 WHERE entry=2000001014;
UPDATE dbscript_string SET content_default="Every item that I have for sale I acquired myself.  You have my personal guarantee of authenticity.", broadcast_text_id=10141 WHERE entry=2000005023;
UPDATE dbscript_string SET content_default="Go, my servant.  Send word of Stonetalon to Apothecary Zamah.", broadcast_text_id=1419 WHERE entry=2000000093;
UPDATE dbscript_string SET content_default="You were right to come.  My wisdom will be yours.", broadcast_text_id=1417 WHERE entry=2000000109;
UPDATE dbscript_string SET content_default="What... what is this? Could this be the answer to my prayers? Elune has granted me a weapon--this scythe--to defeat the demons.", broadcast_text_id=1358 WHERE entry=2000000240;
UPDATE dbscript_string SET content_default="No matter.  You were a fool to help me, and now you will pay!", broadcast_text_id=844 WHERE entry=2000000236;
UPDATE dbscript_string SET content_default="Why have you summoned me so soon?  I haven't yet reached my full power!", broadcast_text_id=843 WHERE entry=2000000235;
UPDATE dbscript_string SET content_default="What?  $N, you served me well, but...", broadcast_text_id=842 WHERE entry=2000000234;
UPDATE dbscript_string SET content_default="Hi Corbett!  Here, you go!  I trust business is faring well at your clothier shop...?", broadcast_text_id=287 WHERE entry=2000000155;
UPDATE dbscript_string SET content_default="Good day, Corbett.  Here's your cheese, fresh made this morning!  And how are things at your shop?", broadcast_text_id=286 WHERE entry=2000000154;
UPDATE dbscript_string SET content_default="Corbett, you there?  Harlan needs another load of knitted goods.  Can you take it to him?", broadcast_text_id=254 WHERE entry=2000000140;
UPDATE dbscript_string SET content_default="Corbett, dear.  Harlan needs a load of knitted shirts and pants as soon as we can manage.", broadcast_text_id=253 WHERE entry=2000000139;
UPDATE dbscript_string SET content_default="Do not be so harsh on the child, Alturus.  Remember that Cedric himself assigned him to you.", broadcast_text_id=15058 WHERE entry=2000000805;
UPDATE dbscript_string SET content_default="The magistrix will be happy to know  I'm  fluent in Thalassian.  Your courtesy is not lost on me.", broadcast_text_id=16875 WHERE entry=2000005275;
UPDATE dbscript_string SET content_default="Back to the topic...  we should focus our attention on these manaforges.  We need to learn what the enemy is doing with them and why.", broadcast_text_id=16876 WHERE entry=2000005276;
UPDATE dbscript_string SET content_default="We've told you all there is to know!  Do you forget that many of us used to be trusted followers of Kael'thas?", broadcast_text_id=16883 WHERE entry=2000005277;
UPDATE dbscript_string SET content_default="I have an idea.  Let's plant this shard in the ground and see what happens.", broadcast_text_id=18289 WHERE entry=2000000182;
UPDATE dbscript_string SET content_default="The evil emanating from the crystal shard has lured one of the colossi.  Put it down quick!", broadcast_text_id=18291 WHERE entry=2000000183;
UPDATE dbscript_string SET content_default="Borgrim, this is no time for drinking.  We just got here.  We need to get settled in.", broadcast_text_id=18813 WHERE entry=2000005679;
UPDATE dbscript_string SET content_default="Thank you, $n.  Now, to perform the test...", broadcast_text_id=19022 WHERE entry=2000000176;
UPDATE dbscript_string SET content_default="$n, I have confirmed that this blood is from the Bonechewer clan of orcs, tainted with demonic power.  I'm afraid, however, that my current equipment can delve no deeper into this mystery...", broadcast_text_id=19025 WHERE entry=2000000179;
UPDATE dbscript_string SET content_default="This cell won't hold me for long.  I will have Illidan's head one way or another.", broadcast_text_id=19394 WHERE entry=2000005475;
UPDATE dbscript_string SET content_default="I've waited for this moment for years.  Illidan and his lapdogs will be destroyed!", broadcast_text_id=20743 WHERE entry=2000005527;
UPDATE dbscript_string SET content_default="Such... dark... energy!  How can this be possible?", broadcast_text_id=13397 WHERE entry=2000008487;
UPDATE dbscript_string SET content_default="Thank you, $n.  It looks like they're going to get along just fine.", broadcast_text_id=13666 WHERE entry=2000000181;

UPDATE dbscript_string SET content_default="An Avatar of Terokk!! To arms!", broadcast_text_id=20268 WHERE entry=2000000025;
UPDATE dbscript_string SET content_default="Your body is mine! Our fates are forever intertwined.", broadcast_text_id=19494 WHERE entry=2000000031;
UPDATE dbscript_string SET content_default="Hear ye, denizens of Tanaris! Let it be known that $N is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $N!", broadcast_text_id=4365 WHERE entry=2000000076;
UPDATE dbscript_string SET content_default="Ok, let's get started.", broadcast_text_id=1610 WHERE entry=2000000096;
UPDATE dbscript_string SET content_default="I believe the Forsaken are misleading the allies of the Horde.... wait... I feel so... dizzy...", broadcast_text_id=1859 WHERE entry=2000000121;
UPDATE dbscript_string SET content_default="The invisibility liquor is ready for you, $n.", broadcast_text_id=1853 WHERE entry=2000000134;
UPDATE dbscript_string SET content_default="Glad to see you're doing so well, Harlan.  And I hope to see you again soon...", broadcast_text_id=264 WHERE entry=2000000149;
UPDATE dbscript_string SET content_default="The beast is slain! All's well in Darkshire!", broadcast_text_id=93 WHERE entry=2000000188;
UPDATE dbscript_string SET content_default="I am free!  I will ask the spirit of fire to return to us so that my people may have the courage to fight their masters!  I thank you, $r.", broadcast_text_id=18356 WHERE entry=2000000201;
UPDATE dbscript_string SET content_default="Into the box me pretties! Thas it. One by one ye go.", broadcast_text_id=8465 WHERE entry=2000000202;
UPDATE dbscript_string SET content_default="If you think you can stop us, you're mistaken, 'friend.'", broadcast_text_id=22046 WHERE entry=2000000315;
UPDATE dbscript_string SET content_default="I fear for the worst, old friend. Within the Dream we fight a new foe, born of an ancient evil. Ysera's noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm and seeks a new host on Azeroth.", broadcast_text_id=10871 WHERE entry=2000000380;
UPDATE dbscript_string SET content_default="You have been gone too long, Malfurion. Peace between the children of Azeroth is tenuous at best. What of my father? Of your brother? Have you any news?", broadcast_text_id=10874 WHERE entry=2000000383;
UPDATE dbscript_string SET content_default="Cenarius fights at my side. Illidan sits atop his throne in the Outland - brooding. I am afraid that the loss to Arthas proved to be his breaking point. Madness has embraced him, Remulos. He replays the events in his mind a thousand times per day, but in his mind, he is the victor and Arthas is utterly defeated. He is too far gone, old friend. I fear that the time may soon come that our bond is tested and it will not be as it was at the Well in Zin-Azshari. ", broadcast_text_id=10876 WHERE entry=2000000384;
UPDATE dbscript_string SET content_default="Gah! Every time I load something into the wagon, it reappears here within moments!", broadcast_text_id=16099 WHERE entry=2000000472;
UPDATE dbscript_string SET content_default="I should have known better than to have given Silanna that tome of cantrips.", broadcast_text_id=16100 WHERE entry=2000000473;
UPDATE dbscript_string SET content_default="Amazing! I think I have found it, $N!", broadcast_text_id=4041 WHERE entry=2000000525;
UPDATE dbscript_string SET content_default="He cannot be defeated. <The relic burns to nothing. The memories it held are now your own. This city was destroyed by a being not of this world.>", broadcast_text_id=4598 WHERE entry=2000000544;
UPDATE dbscript_string SET content_default="Do not taint these ruins, mortal. <You are engulfed in a blinding flash of light. A creature composed entirely of flame is the only thing you can remember seeing.>", broadcast_text_id=4596 WHERE entry=2000000546;
UPDATE dbscript_string SET content_default="The sound of footsteps shuffling echo throughout the cave.", broadcast_text_id=14019 WHERE entry=2000000600;
UPDATE dbscript_string SET content_default="Rawr! Me is Shadow Council magishun! Me come for Warmaul terri... tettritor... Me come for Warmaul land!", broadcast_text_id=15346 WHERE entry=2000000614;
UPDATE dbscript_string SET content_default="I won't be held responsible for the catastrophe that will surely result from the haphazard maintenance of this building.", broadcast_text_id=13574 WHERE entry=2000000648;
UPDATE dbscript_string SET content_default="Turning to face Tuluun, the %s sneers contemptuously.", broadcast_text_id=14381 WHERE entry=2000000662;
UPDATE dbscript_string SET content_default="It looks like it be succulent pork ribs basted with its own delectable juices and a side o' Captain Sander's Secret Sauce - fer dippin'.", broadcast_text_id=13700 WHERE entry=2000000685;
UPDATE dbscript_string SET content_default="They are as cruel as they are powerful - and revel in the destruction of all that exists.", broadcast_text_id=18305 WHERE entry=2000000730;
UPDATE dbscript_string SET content_default="Conscripted from the mo'arg race, these warriors serve as the Legion's rank and file soldiers.", broadcast_text_id=17406 WHERE entry=2000000747;
UPDATE dbscript_string SET content_default="They are fearless and unwaveringly loyal to their master's godlike will.", broadcast_text_id=18308 WHERE entry=2000000748;
UPDATE dbscript_string SET content_default="Cunning and precise, the Wrathguard often protect the Legion's eredar masters.", broadcast_text_id=17398 WHERE entry=2000000759;
UPDATE dbscript_string SET content_default="This is extended to the spirits themselves. They are often quick to anger; it is important that you learn to listen without falling prey to their tempers.", broadcast_text_id=16077 WHERE entry=2000000778;
UPDATE dbscript_string SET content_default="Draenei dog! Did you know that the one you call Saruan wept like a babe as I beat him? A feeling of euphoria coursed through me, knowing that I had a member of high rank in my grasp. Were it not for Sironas' plans for him, I would have tortured him to death... As I do to all draenei that I capture. Alas, I am certain that you will see him again soon...", broadcast_text_id=14537 WHERE entry=2000000896;
UPDATE dbscript_string SET content_default="Twenty years we've been stranded in this hell-hole. It's all I can do not to run screaming through that blasted Portal. I want to see my loved ones again! I want them to know I'm still alive.", broadcast_text_id=18210 WHERE entry=2000001055;
UPDATE dbscript_string SET content_default="It's not him I'm worried about. It's these new rookies around here - and those creepy purple elves they brought with 'em. They ain't even proved themselves yet.", broadcast_text_id=18212 WHERE entry=2000001057;
UPDATE dbscript_string SET content_default="What now, Danath? Can you not see that I am inundated with work as is?", broadcast_text_id=12754 WHERE entry=2000001072;
UPDATE dbscript_string SET content_default="I have a good mind to tear that portal down myself! This is outrageous!", broadcast_text_id=12758 WHERE entry=2000001082;
UPDATE dbscript_string SET content_default="That is the wrong answer, $N. Be off with you.", broadcast_text_id=8393 WHERE entry=2000001228;
UPDATE dbscript_string SET content_default="It was the will of Ragnaros that Obsidion be built. Obsidion will destroy the Blackrock orcs of Blackrock Spire, uniting us with our bretheren in the fiery depths.", broadcast_text_id=4397 WHERE entry=2000001340;
UPDATE dbscript_string SET content_default="You will perish here. <Your mind fills with visions of chaos and destruction.>", broadcast_text_id=4595 WHERE entry=2000001424;
UPDATE dbscript_string SET content_default="Defiler... you will be punished for this incursion. <A symbol of flame radiates from the relic before it crumbles to the earth.>", broadcast_text_id=4600 WHERE entry=2000001428;
UPDATE dbscript_string SET content_default="Your existence is acknowledged. <The relic turns to dust. Your head throbs with newfound wisdom. Something evil lurks in the heart of the mountain.>", broadcast_text_id=4599 WHERE entry=2000001430;
UPDATE dbscript_string SET content_default="You know there are crocilisks in the Canals. They were brought from the swamp as pets, but got thrown in the canals.", broadcast_text_id=156 WHERE entry=2000001907;
UPDATE dbscript_string SET content_default="Farewell. We shall speak again, I'm sure.", broadcast_text_id=1772 WHERE entry=2000002024;
UPDATE dbscript_string SET content_default="Greatmother...Am I...", broadcast_text_id=17113 WHERE entry=2000003090;
UPDATE dbscript_string SET content_default="They... did not, Greatmother. They were killed shortly after I was born. I never knew them. I was raised as a slave. To this day, I carry the name of Thrall.", broadcast_text_id=17122 WHERE entry=2000003092;
UPDATE dbscript_string SET content_default="I have dreamed of this moment all my life, Greatmother. 'Till now, all I've had were Orgrim's stories about my parents and their adventures on Draenor. He was my greatest teacher and dearest friend. He died a hero... They all died as heroes - and for all of them, a song of honor remains.", broadcast_text_id=17928 WHERE entry=2000003096;
UPDATE dbscript_string SET content_default="The boy believed you could be saved, but he didn't know what burns within your soul when in your heart, you know we are the same.", broadcast_text_id=17142 WHERE entry=2000003114;
UPDATE dbscript_string SET content_default="The demon's fire has burnt out in my veins. I have... freed myself.", broadcast_text_id=17152 WHERE entry=2000003118;
UPDATE dbscript_string SET content_default="Bijou lost! SQUAWK! *cough*", broadcast_text_id=5541 WHERE entry=2000005002;
UPDATE dbscript_string SET content_default="They all go to the Spire but none ever come back... just like Bijou.", broadcast_text_id=5544 WHERE entry=2000005006;
UPDATE dbscript_string SET content_default="Ah, this must be him now... no?  Bah!", broadcast_text_id=5960 WHERE entry=2000005018;
UPDATE dbscript_string SET content_default="Wouldn't you like to bring those days back? I have some friends who know just the way to do that...", broadcast_text_id=22052 WHERE entry=2000005022;
UPDATE dbscript_string SET content_default="Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds!  We have it all... delicious food, strong drink, exotic artifacts, fortunes read, amazing prizes and excitement without end!  Don't forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate!  All it takes is five or more and you're on your way to the most wondrous prizes in all of Outland.  Everybody is a winner!", broadcast_text_id=22544 WHERE entry=2000005034;
UPDATE dbscript_string SET content_default="Just don't ask me where I got it...", broadcast_text_id=16059 WHERE entry=2000005045;
UPDATE dbscript_string SET content_default="You want to go do the bounty off of this wanted poster after the shift is over?", broadcast_text_id=16974 WHERE entry=2000005047;
UPDATE dbscript_string SET content_default="Well hand it over and let's see what you've got!", broadcast_text_id=17045 WHERE entry=2000005050;
UPDATE dbscript_string SET content_default="This is the last time that I buy second-hand equipment from an ethereal!", broadcast_text_id=16951 WHERE entry=2000005067;
UPDATE dbscript_string SET content_default="Not a challenge at all it seems. Let us see how you handle your second test. Lysta, bring forth the minions of the Lich King.", broadcast_text_id=1980 WHERE entry=2000005073;
UPDATE dbscript_string SET content_default="Yer wearin down, princess. I can sense it!", broadcast_text_id=22211 WHERE entry=2000005203;
UPDATE dbscript_string SET content_default="Derived from cutting edge Shattered Sun Offensive military technology, it blasts away stubborn stains with ease!", broadcast_text_id=25074 WHERE entry=2000005207;
UPDATE dbscript_string SET content_default="The Darkmoon Faire is the greatest event in all of Outland!", broadcast_text_id=22546 WHERE entry=2000005221;
UPDATE dbscript_string SET content_default="This data will be quite useful for Project Blue Book. Er, I mean, this will be great for my new look.  See if you can gather any more data.", broadcast_text_id=17060 WHERE entry=2000005222;
UPDATE dbscript_string SET content_default="Just sit right back and you'll hear a ta... *hic* a tai... *hic* a taiiii *hic* Damnit!", broadcast_text_id=6409 WHERE entry=2000005233;
UPDATE dbscript_string SET content_default="You need to do what? All this science, I don't understand... Look, this is just my job, five days a week.", broadcast_text_id=17416 WHERE entry=2000005250;
UPDATE dbscript_string SET content_default="Who? The Tauren Chieftains! What? A live performance! Where? The World's End Tavern! When? The top of the hour! BE THERE!", broadcast_text_id=28502 WHERE entry=2000005305;
UPDATE dbscript_string SET content_default="Blathering idiot. You incomprehensibly incompetent buffoon...", broadcast_text_id=21808 WHERE entry=2000005350;
UPDATE dbscript_string SET content_default="You will not harm the $g boy:girl;, Mor'ghor! Quickly, $n, climb on my back!", broadcast_text_id=21825 WHERE entry=2000005355;
UPDATE dbscript_string SET content_default="How dare you take my eye!  I will crush your soul and feed it to my blind and whimpering imps!", broadcast_text_id=19913 WHERE entry=2000005405;
UPDATE dbscript_string SET content_default="Come to my lair, whelp!  Come to me and pay for your insolence!", broadcast_text_id=19914 WHERE entry=2000005406;
UPDATE dbscript_string SET content_default="Where do you think you are you going soldier?  Those are fatal wounds you've got there.  Now, get back in that tent and let the nurse treat you!", broadcast_text_id=16714 WHERE entry=2000005412;
UPDATE dbscript_string SET content_default="Now get out of my way, it's time to send the Burning Legion back to the nether!!", broadcast_text_id=16730 WHERE entry=2000005413;
UPDATE dbscript_string SET content_default="Sniff... That's the spirit soldier... I only wish we had more soldiers like you in this army.  Now go out there and give 'em hell!!", broadcast_text_id=16736 WHERE entry=2000005414;
UPDATE dbscript_string SET content_default="Warbringer, that will require the use of all the hold's infernals. It may leave us vulnerable to a counterattack.", broadcast_text_id=19275 WHERE entry=2000005434;
UPDATE dbscript_string SET content_default="I've rigged a few control consoles down the slope. Get to one quickly and take control of the fel reaver! You'll only have a limited amount of time.", broadcast_text_id=19666 WHERE entry=2000005459;
UPDATE dbscript_string SET content_default="Waste no time, fool! Use our power to kill those that stand in our way! Destroy Karsius before you are subdued!", broadcast_text_id=19503 WHERE entry=2000005473;
UPDATE dbscript_string SET content_default="$N, please take a look at the sample of the Vylestem vine that I took from the caverns, so that you know what to look for...", broadcast_text_id=8923 WHERE entry=2000005664;
UPDATE dbscript_string SET content_default="%s combines the herbs with the moonwell water to create the Ward of Waking.", broadcast_text_id=20517 WHERE entry=2000005667;
UPDATE dbscript_string SET content_default="%s cautiously approaches Watcher Elaira.", broadcast_text_id=20739 WHERE entry=2000005672;
UPDATE dbscript_string SET content_default="Now we call forth the arcane acolyte.", broadcast_text_id=20920 WHERE entry=2000005720;
UPDATE dbscript_string SET content_default="It is over, your search is done. Let fate choose now, the righteous one.", broadcast_text_id=22261 WHERE entry=2000005809;
UPDATE dbscript_string SET content_default="Kael'thas Sunstrider has been defeated by $n and $g his:her; allies.", broadcast_text_id=20778 WHERE entry=2000005918;
UPDATE dbscript_string SET content_default="The time to strike at the remaining blood elves of Tempest Keep is now. Take arms and let A'dal's song of battle empower you!", broadcast_text_id=20779 WHERE entry=2000005919;
UPDATE dbscript_string SET content_default="Did you think that your betrayal would be forgotten? Lost in the carefully planned cover up of my death? Blood of my blood, the blade felt your cruelty long after my heart had stopped beating. And in death, I knew what you had done. But now, the chains of Kel'Thuzad hold me no more. I come to serve justice. I AM ASHBRINGER.", broadcast_text_id=12471 WHERE entry=2000005983;
UPDATE dbscript_string SET content_default="That was life-changing... Excuse me for one minute.", broadcast_text_id=19099 WHERE entry=2000006091;
UPDATE dbscript_string SET content_default="People of the Horde, citizens of Orgrimmar, come, gather round and celebrate a hero of the Horde. On this day, $N, under the auspices of our glorious Warchief, laid a mortal blow against the Black Dragonflight. The brood mother, Onyxia, has been slain!", broadcast_text_id=9491 WHERE entry=2000009039;
UPDATE dbscript_string SET content_default="Your leader takes residence at the doorstep to Naxxramas. Do you think he does not feel the pressure?", broadcast_text_id=12048 WHERE entry=2000009080;
UPDATE dbscript_string SET content_default="It was your leadership that manipulated a grieving child to try and recover the sword. A child that has grown into a man with nothing but vengeance and hatred in his heart! And for what? You are no closer to the sword now than you were five years ago.", broadcast_text_id=12065 WHERE entry=2000009093;
UPDATE dbscript_string SET content_default="Oh dear, Lieutenant General, how ghastly! I would most certainly never. I shall return to my charges, now.", broadcast_text_id=16749 WHERE entry=2000020134;
UPDATE dbscript_string SET content_default="Follow me, good Paladin.  I'll have your barding done faster than I could down a Dwarven stout.  Mmmm... stout.", broadcast_text_id=9776 WHERE entry=2000000063;
UPDATE dbscript_string SET content_default="His lieutenant, Ilkrud Magthrull possesses a tome which might indicate the location of the remaining soulgems.", broadcast_text_id=1475 WHERE entry=2000000086;
UPDATE dbscript_string SET content_default="I can get back to the Stronghold on my own, I think.  Now that you bought me some time, I should be able to stealth out of here.  Who ever you are... thank you.  May Elune bless you always!", broadcast_text_id=10620 WHERE entry=2000000520;
UPDATE dbscript_string SET content_default="Help us, outsider. <The relic crumbles to dust. A vision of eight Dark Iron dwarves performing some sort of ritual fills your head.>", broadcast_text_id=4597 WHERE entry=2000000550;
UPDATE dbscript_string SET content_default="You so smart. Let's do dis now before more come.", broadcast_text_id=15351 WHERE entry=2000000618;
UPDATE dbscript_string SET content_default="Now, let's see...", broadcast_text_id=14281 WHERE entry=2000000856;
UPDATE dbscript_string SET content_default="Time for the Gizleton Caravan to head on out! We'll be back soon but if you cannot wait, head north to Kormek's Hut. We open shop in about an hour.", broadcast_text_id=7506 WHERE entry=2000000874;
UPDATE dbscript_string SET content_default="What manner of fool opens the very thing we were sent to close?", broadcast_text_id=12757 WHERE entry=2000001079;
UPDATE dbscript_string SET content_default="It is time to face your final challenge young warriors! Prepare for your hardest fight yet.", broadcast_text_id=1984 WHERE entry=2000005075;
UPDATE dbscript_string SET content_default="When is pappa coming back from the fights in Warsong? It has been so long... ", broadcast_text_id=10303 WHERE entry=2000005775;
UPDATE dbscript_string SET content_default="I'm listening...", broadcast_text_id=18966 WHERE entry=2000006011;
UPDATE dbscript_string SET content_default="%s cracks the rotten egg open and - to the horror and dismay of all around him - begins to drink from its putrid core.", broadcast_text_id=19098 WHERE entry=2000006090;
UPDATE dbscript_string SET content_default="Be patient, $N. The torch is almost complete.", broadcast_text_id=4448 WHERE entry=2000000019;
UPDATE dbscript_string SET content_default="I pity you, Forsaken.  Your soul is devoid of light.", broadcast_text_id=13685 WHERE entry=2000000257;
UPDATE dbscript_string SET content_default="They will live, if only to see the fruits of their labor: the destruction and chaos that will surely ensue as the legion of Blackrock invade the gorge.", broadcast_text_id=4461 WHERE entry=2000000531;
UPDATE dbscript_string SET content_default="Wrathguard", broadcast_text_id=15998 WHERE entry=2000000755;
UPDATE dbscript_string SET content_default="Klaven doesn't pay me enough to deal with zombies, drones, or whatever he calls 'em.", broadcast_text_id=4018 WHERE entry=2000000795;
UPDATE dbscript_string SET content_default="Eekum Bokum!", broadcast_text_id=36346 WHERE entry=2000001855;
UPDATE dbscript_string SET content_default="This is unforseen.  The being who enchanted this is known to me...", broadcast_text_id=516 WHERE entry=2000002028;
UPDATE dbscript_string SET content_default="New posting going up! Adventurers and heroes, gather round the bulletin board!", broadcast_text_id=15373 WHERE entry=2000005042;
UPDATE dbscript_string SET content_default="Ask me how to get a free drink at the Blue Recluse!", broadcast_text_id=1192 WHERE entry=2000005191;
UPDATE dbscript_string SET content_default="Ask me how to get a free drink at the Blue Recluse!", broadcast_text_id=1192 WHERE entry=2000005197;
UPDATE dbscript_string SET content_default="Spirits watch over you, $r!", broadcast_text_id=15390 WHERE entry=2000005430;
UPDATE dbscript_string SET content_default="I shall use the time wisely, milord. Thank you.", broadcast_text_id=3791 WHERE entry=2000010177;
UPDATE dbscript_string SET content_default="%s takes a big swig of ale.", broadcast_text_id=1857 WHERE entry=2000000119;
UPDATE dbscript_string SET content_default="Hey, Harlan.  Here's a load of knitted cloth for you.", broadcast_text_id=259 WHERE entry=2000000145;
UPDATE dbscript_string SET content_default="Oomph!  Here's another load of supplies, Harlan.  It must be selling fast!", broadcast_text_id=260 WHERE entry=2000000146;
UPDATE dbscript_string SET content_default="Ah, much appreciated, Corbett.  We'll get these on the racks immediately.", broadcast_text_id=261 WHERE entry=2000000148;
UPDATE dbscript_string SET content_default="Good day, Elling!  Hullo Elaine!  Let me have a wheel of bleu cheese, eh?", broadcast_text_id=284 WHERE entry=2000000153;
UPDATE dbscript_string SET content_default="%s bursts open!", broadcast_text_id=1460 WHERE entry=2000000164;
UPDATE dbscript_string SET content_default="Jero'me falls into a drunken sleep.", broadcast_text_id=17512 WHERE entry=2000000342;
UPDATE dbscript_string SET content_default="Jero'me wakes up and slowly rises to his feet.", broadcast_text_id=17513 WHERE entry=2000000343;
UPDATE dbscript_string SET content_default="Come, $N. The lake is just around the bend.", broadcast_text_id=10866 WHERE entry=2000000375;
UPDATE dbscript_string SET content_default="Remulos, old friend. It is good to see you once more. I knew that the message would find its way to you - one way or another.", broadcast_text_id=10869 WHERE entry=2000000378;
UPDATE dbscript_string SET content_default="Aye, Remulos. Prepare the mortal races.", broadcast_text_id=10873 WHERE entry=2000000382;
UPDATE dbscript_string SET content_default="Remulos, I am being drawn back... Tyrande... send her my love... Tell her I am safe. Tell her... Tell her I will return... Farewell...", broadcast_text_id=10878 WHERE entry=2000000385;
UPDATE dbscript_string SET content_default="%s glances from guard to guard.", broadcast_text_id=14809 WHERE entry=2000000478;
UPDATE dbscript_string SET content_default="%s surveys the small ranger practice ground with a condescending smirk.", broadcast_text_id=14810 WHERE entry=2000000479;
UPDATE dbscript_string SET content_default="%s inclines his head slightly to the pair of guardians in greeting.", broadcast_text_id=14811 WHERE entry=2000000480;
UPDATE dbscript_string SET content_default="%s arches a sculpted brow at the guards, a disapproving scowl on his face.", broadcast_text_id=14808 WHERE entry=2000000481;
UPDATE dbscript_string SET content_default="Feralas: A History... Hmmmm... Let me examine this for a moment.", broadcast_text_id=4039 WHERE entry=2000000523;
UPDATE dbscript_string SET content_default="Yes, Zhanaa, it's me!  Your signal is weak.", broadcast_text_id=13687 WHERE entry=2000000652;
UPDATE dbscript_string SET content_default="Zhanaa!  Gah, I have to get this thing fixed!", broadcast_text_id=13692 WHERE entry=2000000654;
UPDATE dbscript_string SET content_default="The %s sighs disgustedly as he turns back to his work.", broadcast_text_id=14384 WHERE entry=2000000664;
UPDATE dbscript_string SET content_default="%s begins to perform an arcane scrying.", broadcast_text_id=14901 WHERE entry=2000000802;
UPDATE dbscript_string SET content_default="Your discs are now ready!  Engage the Discs of Norgannon once again to retrieve them!", broadcast_text_id=3743 WHERE entry=2000000824;
UPDATE dbscript_string SET content_default="Please, $n.  You must take the Heart of Fury somewhere safe... you must take it to A'dal!", broadcast_text_id=19870 WHERE entry=2000001006;
UPDATE dbscript_string SET content_default="%s cracks open, filling the nest with yolk.", broadcast_text_id=16150 WHERE entry=2000001124;
UPDATE dbscript_string SET content_default="Fools, I knew that if I played upon my brother's feeble emotions, he would send 'rescuers.'", broadcast_text_id=4394 WHERE entry=2000001337;
UPDATE dbscript_string SET content_default="Please!  I must feed on something soon... A mana crystal.... a shard... anything!  The pain is unbearable!", broadcast_text_id=12835 WHERE entry=2000005036;
UPDATE dbscript_string SET content_default="Right.  We just busted our tails to haul all of this stuff up here, and you want to work more?", broadcast_text_id=18816 WHERE entry=2000005056;
UPDATE dbscript_string SET content_default="Billy says Fizzles used to be a great wizard. But he got turned into a rabbit when one of his spells went bad.", broadcast_text_id=1091 WHERE entry=2000005184;
UPDATE dbscript_string SET content_default="Hey, harbinger, how's that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you're prompt with the results!", broadcast_text_id=25085 WHERE entry=2000005201;
UPDATE dbscript_string SET content_default="I'm picking up trace amounts of chroniton particles.  Hmm, if we use a reverse phase inducer, while inverting our own chronosphere, we might be able to eliminate the particles. Of course, that means we need to build a chronosphere...", broadcast_text_id=17021 WHERE entry=2000005258;
UPDATE dbscript_string SET content_default="%s roars at Terenthis to get his attention.", broadcast_text_id=1226 WHERE entry=2000005385;
UPDATE dbscript_string SET content_default="%s begins to moan and roar at Terenthis while stomping his paws on the ground.", broadcast_text_id=1228 WHERE entry=2000005387;
UPDATE dbscript_string SET content_default="%s begins to cast a spell on Grimclaw.", broadcast_text_id=1246 WHERE entry=2000005389;
UPDATE dbscript_string SET content_default="%s roars at Terenthis more, but this time the druid seems to understand the bear.", broadcast_text_id=1231 WHERE entry=2000005391;
UPDATE dbscript_string SET content_default="%s roars in acknowledgement at Terenthis.", broadcast_text_id=1233 WHERE entry=2000005393;
UPDATE dbscript_string SET content_default="Think of our younglings, Gul'dan! You will destroy us all!", broadcast_text_id=18699 WHERE entry=2000005454;
UPDATE dbscript_string SET content_default="And... if we do not?", broadcast_text_id=19695 WHERE entry=2000005467;
UPDATE dbscript_string SET content_default="This wanted poster has a bounty on bonelashers.  You think I should do that?", broadcast_text_id=16971 WHERE entry=2000005685;
UPDATE dbscript_string SET content_default="%s listens to $N's report...", broadcast_text_id=981 WHERE entry=2000005777;
UPDATE dbscript_string SET content_default="%s begins to sputter as its engine malfunctions.", broadcast_text_id=20103 WHERE entry=2000005788;
UPDATE dbscript_string SET content_default="%s begins to cast a spell as you take the cloak from him.", broadcast_text_id=1249 WHERE entry=2000009047;
UPDATE dbscript_string SET content_default="NO! Shhhh! Just shut up. Goretooth is coming!", broadcast_text_id=4668 WHERE entry=2000009059;
UPDATE dbscript_string SET content_default="AIEEE! What are you doing?! I'm still ALIVE, damn you!", broadcast_text_id=16751 WHERE entry=2000020130;
UPDATE dbscript_string SET content_default="The spirits call... I am consumed.", broadcast_text_id=15704 WHERE entry=2000009015;
UPDATE dbscript_string SET content_default="Thank you, great spirit. Thank you!", broadcast_text_id=6599 WHERE entry=2000000058;
UPDATE dbscript_string SET content_default="Gird yourself, $N, for the demon in this orb is a fel beast.", broadcast_text_id=2629 WHERE entry=2000000032;
UPDATE dbscript_string SET content_default="It's all here... how the raven's followers captured and subdued the spirits of rivals, trapping them forever within stone statues! The tablet even mentions the raven god's name -- Anzu. I'd thought it was lost to history!", broadcast_text_id=20756 WHERE entry=2000000072;
UPDATE dbscript_string SET content_default="There's something else here, too. After a description of a bloody battle and the downfall of the raven, there's a prophecy. Anzu will haunt the dreams of his enemies, twisting them to effect a return to this world...", broadcast_text_id=20757 WHERE entry=2000000073;
UPDATE dbscript_string SET content_default="Viera Sunwhisper scurries away, attempting to flee from Twinkle.", broadcast_text_id=13610 WHERE entry=2000000391;
UPDATE dbscript_string SET content_default="I think I can make it to Brackenwall on my own. They've got the cargo at the top of the tower. Be careful!", broadcast_text_id=13500 WHERE entry=2000000486;
UPDATE dbscript_string SET content_default="That is wonderous, Rimblat! Even this foul, sundered earth is not beyond healing.", broadcast_text_id=11945 WHERE entry=2000000861;
UPDATE dbscript_string SET content_default="Gimme my dolly!!", broadcast_text_id=694 WHERE entry=2000005062;
UPDATE dbscript_string SET content_default="O'course I'm talkin to myself. Only way to get decent conversation in this city.", broadcast_text_id=1108 WHERE entry=2000005105;
UPDATE dbscript_string SET content_default="Deja vu.  For a moment, I thought I was back home... before the plague...", broadcast_text_id=1112 WHERE entry=2000005108;
UPDATE dbscript_string SET content_default="Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on his throne.", broadcast_text_id=1155 WHERE entry=2000005136;
UPDATE dbscript_string SET content_default="The magical wards at that point should be supported enough by the energy flux to contain the entity.", broadcast_text_id=207 WHERE entry=2000005151;
UPDATE dbscript_string SET content_default="Sure, Paige. Just be gentle.", broadcast_text_id=589 WHERE entry=2000005181;
UPDATE dbscript_string SET content_default="This is a shiney rock, I'll put it in my bucket. Ok, I just need a few more...", broadcast_text_id=10279 WHERE entry=2000005325;
UPDATE dbscript_string SET content_default="%s's soft voice trails away into the mists, \"Know that I love you always...\"", broadcast_text_id=1285 WHERE entry=2000005344;
UPDATE dbscript_string SET content_default="Release me immediately or face my wrath!", broadcast_text_id=19395 WHERE entry=2000005474;
UPDATE dbscript_string SET content_default="If you're here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin.", broadcast_text_id=2049 WHERE entry=2000005634;
UPDATE dbscript_string SET content_default="Now that you have had a chance to study the imp, let us move on to the next minion you will be able to summon, the voidwalker.", broadcast_text_id=2052 WHERE entry=2000005637;
UPDATE dbscript_string SET content_default="This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent's life.", broadcast_text_id=2053 WHERE entry=2000005638;
UPDATE dbscript_string SET content_default="All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield.", broadcast_text_id=2055 WHERE entry=2000005640;
UPDATE dbscript_string SET content_default="Study hard and you might one day be able to summon one on your own, but for now it's time to move on to the felhunter.", broadcast_text_id=2056 WHERE entry=2000005641;
UPDATE dbscript_string SET content_default="I'm going to train you to help $n with a very important task. After that, I promise you'll be free to return home.", broadcast_text_id=20740 WHERE entry=2000005673;
UPDATE dbscript_string SET content_default="%s gestures to the pitcher of water sitting on the edge of the well.", broadcast_text_id=1528 WHERE entry=2000009044;
UPDATE dbscript_string SET content_default="%s hums a melody over the well.", broadcast_text_id=22355 WHERE entry=2000009044;
UPDATE dbscript_string SET content_default="%s smiles as she continues to draw water from the well.", broadcast_text_id=22357 WHERE entry=2000009044;
UPDATE dbscript_string SET content_default="Oh, it's just terribly, terribly, awful! You will just DIE when you see it, Vivian.", broadcast_text_id=4679 WHERE entry=2000009066;
UPDATE dbscript_string SET content_default="And might I add, that dress is lovely! You must tell me where you got it from.", broadcast_text_id=12144 WHERE entry=2000009103;
UPDATE dbscript_string SET content_default="Lovely song, isn't it?", broadcast_text_id=11089 WHERE entry=2000000009;
UPDATE dbscript_string SET content_default="Spirits of Water, I give you praise, and I beg of you a favor. You have heard $N's pleas, and I trust $ghis:her; intent is noble. Please, will you aid us?", broadcast_text_id=6586 WHERE entry=2000000057;
UPDATE dbscript_string SET content_default="I have been expecting you, young one. Come closer - my eyes are not as sharp as they once were.", broadcast_text_id=17101 WHERE entry=2000003088;
UPDATE dbscript_string SET content_default="Yes, you move like my son. You have his broad shoulders - ahh, and your mother's fierce eyes.", broadcast_text_id=17120 WHERE entry=2000003089;
UPDATE dbscript_string SET content_default="There is no doubt - you are the heir of Durotan... my grandson. Draka told me she was with child before she and your father left our world, but I never dared dream that they would survive...", broadcast_text_id=17123 WHERE entry=2000003091;
UPDATE dbscript_string SET content_default="Go'el. You are Go'el, son of Durotan - rightful chieftain of the Frostwolves. This day, grandson - you are the great joy of my heart.", broadcast_text_id=17927 WHERE entry=2000003095;
UPDATE dbscript_string SET content_default="I see that you hold the Doomhammer. Have all of our greatest heroes fallen, grandson?", broadcast_text_id=17929 WHERE entry=2000003097;
UPDATE dbscript_string SET content_default="What of Grommash? What of Hellscream?", broadcast_text_id=17930 WHERE entry=2000003099;
UPDATE dbscript_string SET content_default="Blessed spirits! For twenty years, all we knew was that Grom was the first to drink from the cursed chalice and bring damnation down upon our people... It is the only truth his son, Garrosh has ever known.", broadcast_text_id=17129 WHERE entry=2000003101;
UPDATE dbscript_string SET content_default="But isn't that what caused the initial problems with Adept Syleria's magical formulae?", broadcast_text_id=214 WHERE entry=2000005160;
UPDATE dbscript_string SET content_default="I'm surrounded by idiots!", broadcast_text_id=16874 WHERE entry=2000005274;
UPDATE dbscript_string SET content_default="I doubt you have had much occasion to see such a creature. These demonic equines will make your travels much faster by acting as your mount as long as you control them. However, they are difficult to control, so be sure you are ready before attempting it.", broadcast_text_id=2059 WHERE entry=2000005644;





















