-- classic is missing interrupt immunity on bosses, some wrong gold values (nefarian is a poor fuck in classicmangos)
UPDATE `creature_template` SET `CreatureTypeFlags`='76', `PowerMultiplier`='20', `DamageMultiplier`='35', `SchoolImmuneMask`='4' WHERE `entry`='11583'; -- Nefarian (70D)
UPDATE `creature_template` SET `DamageMultiplier`='25' WHERE `entry`='11981'; -- Flamegor (38D)
UPDATE `creature_template` SET `DamageMultiplier`='7' WHERE `entry`='12416'; -- Blackwing Legionnaire (12D)
UPDATE `creature_template` SET `DamageMultiplier`='4' WHERE `entry`='12420'; -- Blackwing Mage (7D)
UPDATE `creature_template` SET `DamageMultiplier`='14' WHERE `entry`='12422'; -- Death Talon Dragonspawn (24D)
UPDATE `creature_template` SET `DamageMultiplier`='5' WHERE `entry`='13996'; -- Blackwing Technician (8.8D)
UPDATE `creature_template` SET `MinLevel`='61', `MaxLevel`='61', `DamageMultiplier`='1' WHERE `entry`='14081'; -- Demon Portal (should be 1 and scale due to summon spell?, is level 61 in sniff) (0.9D)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='15', `MeleeBaseAttackTime`='2300' WHERE `entry`='14101'; -- Enraged Felguard (17D)
UPDATE `creature_template` SET `MechanicImmuneMask`='65861' WHERE `entry`='14261'; -- Blue Drakonid (5D)
UPDATE `creature_template` SET `DamageMultiplier`='5', `MechanicImmuneMask`='82261' WHERE `entry`='14262'; -- Green Drakonid (8.4D)
UPDATE `creature_template` SET `DamageMultiplier`='5', `MechanicImmuneMask`='65861' WHERE `entry`='14263'; -- Bronze Drakonid (4D)
UPDATE `creature_template` SET `DamageMultiplier`='5', `MechanicImmuneMask`='65877' WHERE `entry`='14264'; -- Red Drakonid (8.4D)
UPDATE `creature_template` SET `MechanicImmuneMask`='65861' WHERE `entry`='14265'; -- Black Drakonid (5D)
UPDATE `creature_template` SET `DamageMultiplier`='3' WHERE `entry`='14401'; -- Master Elemental Shaper Krixix (5.2D)
UPDATE `creature_template` SET `DamageMultiplier`='25' WHERE `entry`='14601'; -- Ebonroc (45D)
UPDATE `creature_template` SET `DamageMultiplier`='5' WHERE `entry`='14605'; -- Bone Construct (2.5D)
UPDATE `creature_template` SET `UnitFlags`='33555200' WHERE `entry`='16604'; -- Blackwing Spell Marker (33587970 wrong, scale 3 also wrong)

