-- classicmangos has no immunities on boss mobs, (c.643 unitflags 64), sneed is poor and has no pockets in classic
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='594'; -- Defias Henchman (1D) (0.974755A)
UPDATE `creature_template` SET `PowerMultiplier`='1', `DamageMultiplier`='1.2' WHERE `entry`='596'; -- Brainwashed Noble (4D) (1A) (attacktimer should be 2000, not 1500)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='598'; -- Defias Miner (1D) (0.970588A) - level 17-18 not 18-18
UPDATE `creature_template` SET `DamageMultiplier`='1.2' WHERE `entry`='599'; -- Marisa du'Paige (1.25D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='1', `ArmorMultiplier`='1' WHERE `entry`='619'; -- Defias Conjurer (1.18D) (0.97389A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='622'; -- Goblin Engineer (1.7D) (0.979192A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='623'; -- Skeletal Miner (1D) (0.978261A)
UPDATE `creature_template` SET `MechanicImmuneMask`='8388624' WHERE `entry`='626'; -- Foreman Thistlenettle (1.2D) (1A) -> was made normal mob, no need for extensive immunities
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='634'; -- Defias Overseer (1.7D) (0.978261A)
UPDATE `creature_template` SET `DamageMultiplier`='2.45' WHERE `entry`='639'; -- Edwin VanCleef (2.5D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='1.7' WHERE `entry`='641'; -- Goblin Woodcarver (3D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='2.45' WHERE `entry`='644'; -- Rhahk'Zor (2.5D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='2.45' WHERE `entry`='645'; -- Cookie (2.5D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='2.45' WHERE `entry`='646'; -- Mr. Smite (2.5D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='3' WHERE `entry`='647'; -- Captain Greenskin (2.5D) (1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='657'; -- Defias Pirate (1.7D) (0.980047A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='1725'; -- Defias Watchman (1D) (0.977273A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='1', `ArmorMultiplier`='1' WHERE `entry`='1726'; -- Defias Magician (1.18D) (0.977612A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='1727'; -- Defias Worker (1D) (0.975936A)
UPDATE `creature_template` SET `DamageMultiplier`='1.7' WHERE `entry`='1732'; -- Defias Squallshaper (1.68D) (1.51584A)
UPDATE `creature_template` SET `DamageMultiplier`='2.45' WHERE `entry`='1763'; -- Gilnid (2.5D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='1.7' WHERE `entry`='3947'; -- Goblin Shipbuilder (3D) (1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='4416'; -- Defias Strip Miner (1D) (0.979192A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='4417'; -- Defias Taskmaster (1.7D) (0.979192A)
UPDATE `creature_template` SET `DamageMultiplier`='1.7' WHERE `entry`='4418'; -- Defias Wizard (2D) (1A)

