-- classicmangos has alot of wrong faction 89 vs 67 for some of these npcs
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='3.7' WHERE `entry`='10381'; -- Ravaged Cadaver (4D) (1A) [NOBESTIARY]
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10382'; -- Mangled Cadaver (3.6D) (1A)
UPDATE `creature_template` SET `Faction`='21', `MinLootGold`='0', `MaxLootGold`='0' WHERE `entry`='10383'; -- Broken Cadaver (1D) (1A) [NOBESTIARY]
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='1' WHERE `entry`='10384'; -- Spectral Citizen (3.6D) (0.991584A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='3.7' WHERE `entry`='10385'; -- Ghostly Citizen (4D) (1A) [NOBESTIARY]
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='10390'; -- Skeletal Guardian (1.8D) (0.991849A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='10391'; -- Skeletal Berserker (1.75D) (0.992308A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10405'; -- Plague Ghoul (4.8D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='4.9' WHERE `entry`='10406'; -- Ghoul Ravener (5D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10407'; -- Fleshflayer Ghoul (5D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='1.25' WHERE `entry`='10408'; -- Rockwing Gargoyle (3.8D) (1.24454A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='3.9', `ArmorMultiplier`='1.25' WHERE `entry`='10409'; -- Rockwing Screecher (4D) (1.24448A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='3.9', `ArmorMultiplier`='1' WHERE `entry`='10412'; -- Crypt Crawler (4D) (0.992261A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='1' WHERE `entry`='10413'; -- Crypt Beast (4D) (0.960169A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10414'; -- Patchwork Horror (6D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10416'; -- Bile Spewer (6D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='6.1' WHERE `entry`='10417'; -- Venom Belcher (6D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='1' WHERE `entry`='10418'; -- Crimson Guardsman (3.8D) (0.99214A)
UPDATE `creature_template` SET `DamageMultiplier`='3.9', `ArmorMultiplier`='1' WHERE `entry`='10421'; -- Crimson Defender (4D) (0.992232A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='10424'; -- Crimson Gallant (4D) (0.96065A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='10426'; -- Crimson Inquisitor (4D) (0.96065A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10435'; -- Magistrate Barthilas (7.5D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='7.25' WHERE `entry`='10436'; -- Baroness Anastari (7.3D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='1.25' WHERE `entry`='10437'; -- Nerub'enkan (7.5D) (1.24479A)
UPDATE `creature_template` SET `DamageMultiplier`='6' WHERE `entry`='10438'; -- Maleki the Pallid (6D) (1A) - not 1, as `MinMeleeDmg`='448', `MaxMeleeDmg`='624'
UPDATE `creature_template` SET `Faction`='21', `PowerMultiplier`='2' WHERE `entry`='10439'; -- Ramstein the Gorger (9D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10463'; -- Shrieking Banshee (3.8D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='3.9' WHERE `entry`='10464'; -- Wailing Banshee (4D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='1.2', `MinLootGold`='534', `MaxLootGold`='2669' WHERE `entry`='10516'; -- The Unforgiven (3.7D) (1.20237A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10558'; -- Hearthsinger Forresten (4D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10808'; -- Timmy the Cruel (13D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='2' WHERE `entry`='10809'; -- Stonespine (5D) (1.97969A)
UPDATE `creature_template` SET `MaxLootGold`='2307' WHERE `entry`='10813'; -- Balnazzar (9D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='10997'; -- Cannon Master Willey (7D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='6.75' WHERE `entry`='11032'; -- Malor the Zealous (6.8D) (1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `ArmorMultiplier`='1' WHERE `entry`='11043'; -- Crimson Monk (5.5D) (0.265102A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='11054'; -- Crimson Rifleman (1D) (0.99214A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='8.5', `MeleeBaseAttackTime`='2000' WHERE `entry`='11058'; -- Fras Siabi (9D) (1A)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='11082'; -- Stratholme Courier (4D) (1A) [NOBESTIARY]
UPDATE `creature_template` SET `PowerMultiplier`='3' WHERE `entry`='11120'; -- Crimson Hammersmith (6D) (1A)
UPDATE `creature_template` SET `Faction`='16', `DamageMultiplier`='8.25', `MeleeBaseAttackTime`='2200', `MaxLootGold`='2176' WHERE `entry`='11143'; -- Postmaster Malown (16D) (1A)
UPDATE `creature_template` SET `Faction`='21', `ArmorMultiplier`='1' WHERE `entry`='11197'; -- Mindless Skeleton (1D) (0.992308A)
UPDATE `creature_template` SET `MinLevel`='60', `MaxLevel`='60', `SpeedWalk`='1', `PowerMultiplier`='2', `DamageMultiplier`='7', `MinLootGold`='1629', `MaxLootGold`='2132' WHERE `entry`='15773'; -- Christmas Cannon Master Willey (1D) (1A)

