-- Fix wrong unit class for 147 creatures. (129 changed)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='450'; -- Defias Renegade Mage (1H)(1P)(0.97D)(1A)
UPDATE `creature_template` SET `MinLootGold`='68', `MaxLootGold`='145' WHERE `entry`='815'; -- Bookie Herod (1.1H)(1P)(1D)(1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='1036'; -- Dragonmaw Centurion (1.05H)(1P)(1D)(0.983683A) - unitclass 2 in tbcbruteforce
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='1854'; -- High Priest Thel'danis (1.35H)(2P)(2D)(1A)
UPDATE `creature_template` SET `MinLootGold`='47' WHERE `entry`='1896'; -- Moonrage Elder (1H)(1P)(1D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `ArmorMultiplier`='1' WHERE `entry`='2160'; -- Gravelflint Geomancer (1.02H)(1P)(1.11D)(1.525A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='2647'; -- Vilebranch Soul Eater (1.2H)(1P)(1D)(0.991365A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MaxLootGold`='63' WHERE `entry`='3799'; -- Severed Druid (1.05H)(1P)(1.3D)(1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='4344'; -- Mottled Drywallow Crocolisk (1.15H)(1P)(1D)(0.967699A)
UPDATE `creature_template` SET `ExtraFlags`='2' WHERE `entry`='4980'; -- Paval Reethe (1.1H)(1P)(1D)(1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='5647'; -- Sandfury Firecaller (1.2H)(2P)(1D)(0.970221A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MaxLootGold`='305' WHERE `entry`='5981'; -- Portal Seeker (1.3H)(1P)(2D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='1' WHERE `entry`='6213'; -- Irradiated Invader (3H)(2.5P)(1.3D)(1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='6246'; -- Latherion (1H)(1P)(1D)(1.33333A)
UPDATE `creature_template` SET `MinLevel`='40', `DamageMultiplier`='1', `ArmorMultiplier`='1' WHERE `entry`='6550'; -- Mana Surge (1.15H)(1P)(1.4D)(1.1118A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000' WHERE `entry`='7073'; -- Arados the Damned (1.1H)(1P)(1.5D)(1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='7370'; -- Restless Shade (1H)(1P)(1D)(0.977077A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `SkinningLootId`='0' WHERE `entry`='7411'; -- Spirit of Sathrah (1H)(1P)(0.8D)(1A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='7872'; -- Death's Head Cultist (1.15H)(2P)(1D)(0.986619A)
UPDATE `creature_template` SET `ArmorMultiplier`='1' WHERE `entry`='7874'; -- Razorfen Thornweaver (1.1H)(2P)(1D)(0.991079A)
UPDATE `creature_template` SET `HealthMultiplier` = 1, `DamageMultiplier`='1', `PowerMultiplier`='1', `MaxLootGold`='576' WHERE `entry`='8075'; -- Edana Hatetalon (3H)(2P)(2D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='8138'; -- Sul'lithuz Broodling (0.3H)(1P)(1.5D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000' WHERE `entry`='8443'; -- Avatar of Hakkar (6H)(1P)(6D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='3.5', `MaxLootGold`='761' WHERE `entry`='10394'; -- Black Guard Sentry (3H)(2P)(4D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='3', `DamageMultiplier`='1', `ArmorMultiplier`='1' WHERE `entry`='10579'; -- Kirtonos the Herald (Spell Visual) (3H)(1P)(14D)(0.811132A)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='10699'; -- Carrion Scarab (0.5H)(1P)(0.6D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MinLootGold`='147', `MaxLootGold`='761', `MechanicImmuneMask`='1' WHERE `entry`='11600'; -- Irondeep Shaman (0.5H)(1.5P)(2D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MinLootGold`='147', `MaxLootGold`='761', `MechanicImmuneMask`='1' WHERE `entry`='11604'; -- Whitewhisker Geomancer (0.5H)(0.5P)(2D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MaxLootGold`='786', `MechanicImmuneMask`='1' WHERE `entry`='11657'; -- Morloch (1H)(2P)(2.4D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MaxLootGold`='305', `MechanicImmuneMask`='1' WHERE `entry`='11675'; -- Snowblind Windcaller (1.3H)(1P)(0.6D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MinLootGold`='152', `MaxLootGold`='761', `MechanicImmuneMask`='1' WHERE `entry`='11677'; -- Taskmaster Snivvle (1H)(1P)(1.6D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='1' WHERE `entry`='11679'; -- Winterax Witch Doctor (4.5H)(1P)(7D)(1A)
UPDATE `creature_template` SET `HeroicEntry` = 22787, `MinLevel`='53', `MaxLevel`='54', `DamageMultiplier`='1', `MinLootGold`='61', `MaxLootGold`='305', `MechanicImmuneMask`='1' WHERE `entry`='11837'; -- Wildpaw Shaman (1.3H)(1P)(0.6D)(1A)
UPDATE `creature_template` SET `HeroicEntry` = 22786, `MinLevel`='56', `MaxLevel`='57', `DamageMultiplier`='1', `MinLootGold`='63', `MaxLootGold`='316', `MechanicImmuneMask`='1' WHERE `entry`='11838'; -- Wildpaw Mystic (1.35H)(1P)(0.5D)(1A)
UPDATE `creature_template` SET `expansion` = 0, `UnitFlags`='0', `CreatureTypeFlags`='0', `Rank`='1', `HealthMultiplier`='40', `PowerMultiplier`='12', `DamageMultiplier`='1' WHERE `entry`='11949'; -- Captain Balinda Stonehearth (30H)(30P)(1.6D)(1A) - 100,600/172,320
UPDATE `creature_template` SET `PowerMultiplier`='2', `DamageMultiplier`='1', `MechanicImmuneMask`='1' WHERE `entry`='12157'; -- Winterax Shadow Hunter (3H)(1P)(7D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MinLootGold`='28', `MaxLootGold`='138' WHERE `entry`='12976'; -- Kolkar Waylayer (1.1H)(1P)(1.2D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MinLootGold`='143', `MaxLootGold`='713', `MechanicImmuneMask`='1', `MeleeBaseAttackTime`='2000' WHERE `entry`='13096'; -- Coldmine Explorer (0.4H)(2P)(6D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MechanicImmuneMask`='1' WHERE `entry`='13097'; -- Coldmine Surveyor (0.4H)(2P)(1.7D)(1A)
UPDATE `creature_template` SET `HeroicEntry` = 22749, `MinLevel`='54', `MaxLevel`='55', `UnitFlags`='0', `DamageMultiplier`='1' WHERE `entry`='13098'; -- Irondeep Surveyor (0.4H)(2P)(1.7D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MechanicImmuneMask`='1' WHERE `entry`='13099'; -- Irondeep Explorer (0.4H)(2P)(1.7D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MechanicImmuneMask`='1' WHERE `entry`='13236'; -- Primalist Thurloga (12H)(12P)(2D)(1A)
UPDATE `creature_template` SET `HeroicEntry` = 22629, `UnitFlags` = 576, `MinLevel`='61', `MaxLevel`='61', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `Expansion` = 0, `SpeedWalk` = 4, `SpeedRun` = 2.14286, ExtraFlags = 0 WHERE `entry`='13256'; -- Lokholar the Ice Lord (50H)(8P)(2.5D)(1A)
UPDATE `creature_template` SET `MinLevel`='71', `MaxLevel`='71', `UnitFlags` = 576, `SpeedWalk` = 4, `SpeedRun` = 2.14286, ExtraFlags = 0  WHERE `entry` = 22629; -- Lokholar the Ice Lord (1)
UPDATE `creature_template` SET `MechanicImmuneMask`='1' WHERE `entry`='13284'; -- Frostwolf Shaman (8H)(8P)(1.6D)(1A)
UPDATE `creature_template` SET `HeroicEntry` = 22627, `UnitFlags` = 576, `Faction` = 1594, `MinLevel`='61', `MaxLevel`='61', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `Expansion` = 0, `SpeedWalk` = 4, `SpeedRun` = 2.14286, ExtraFlags = 0 WHERE `entry`='13419'; -- Ivus the Forest Lord (50H)(15P)(4D)(1A)
UPDATE `creature_template` SET `MinLevel`='71', `MaxLevel`='71', `Faction` = 1594, `UnitFlags` = 576, `SpeedWalk` = 4, `SpeedRun` = 2.14286, ExtraFlags = 0, UnitClass = 2 WHERE `entry` = 22627; -- Ivus the Forest Lord (1)
UPDATE `creature_template` SET `MechanicImmuneMask`='1' WHERE `entry`='13442'; -- Arch Druid Renferal (12H)(12P)(2D)(1A)
UPDATE `creature_template` SET `MechanicImmuneMask`='1' WHERE `entry`='13443'; -- Druid of the Grove (8H)(8P)(2D)(1A)
UPDATE `creature_template` SET `MinLevel`='56', `MaxLevel`='57', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `Faction` = 1214, `SpeedWalk` = 1, `expansion` = 0 WHERE `entry`='13537'; -- Seasoned Coldmine Surveyor (0.5H)(2P)(2.4D)(1A)
UPDATE `creature_template` SET `MinLevel`='66', `MaxLevel`='67', `SpeedWalk` = 1 WHERE `entry` = 22754; -- Seasoned Coldmine Surveyor (1)
UPDATE `creature_template` SET `MinLevel`='58', `MaxLevel`='59', `DamageMultiplier`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13538'; -- Veteran Coldmine Surveyor (0.6H)(2P)(2.4D)(1A)
UPDATE `creature_template` SET `SpeedWalk` = 1 WHERE `entry` = 22773; -- Veteran Coldmine Surveyor (1)
UPDATE `creature_template` SET `MinLevel`='60', `MaxLevel`='60', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `MechanicImmuneMask`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13539'; -- Champion Coldmine Surveyor (0.7H)(2P)(4D)(1A)
UPDATE `creature_template` SET `MinLevel`='70', `MaxLevel`='70', `SpeedWalk` = 1 WHERE `entry` = 22532; -- Champion Coldmine Surveyor (1)
UPDATE `creature_template` SET `MinLevel`='56', `MaxLevel`='57', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `SpeedWalk` = 1 WHERE `entry`='13540'; -- Seasoned Irondeep Explorer (0.5H)(1P)(2.5D)(1A)
UPDATE `creature_template` SET `MinLevel`='66', `MaxLevel`='67', `SpeedWalk` = 1 WHERE `entry` = 22755; -- Seasoned Irondeep Explorer (1)
UPDATE `creature_template` SET `MinLevel`='58', `MaxLevel`='59', `PowerMultiplier`='2', `DamageMultiplier`='1', `SpeedWalk` = 1 WHERE `entry`='13541'; -- Veteran Irondeep Explorer (0.6H)(1P)(1.3D)(1A)
UPDATE `creature_template` SET `MinLevel`='68', `MaxLevel`='69', `PowerMultiplier`='2', `SpeedWalk` = 1 WHERE `entry` = 22774; -- Veteran Irondeep Explorer (1)
UPDATE `creature_template` SET `MinLevel`='60', `MaxLevel`='60', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `SpeedWalk` = 1, `expansion` = 0 WHERE `entry`='13542'; -- Champion Irondeep Explorer (0.7H)(1P)(3D)(1A)
UPDATE `creature_template` SET `MinLevel`='70', `MaxLevel`='70', `SpeedWalk` = 1 WHERE `entry` = 22534; -- Champion Irondeep Explorer (1)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MaxLootGold`='761', `MechanicImmuneMask`='1', `MeleeBaseAttackTime`='2000', `expansion` = 0 WHERE `entry`='13546'; -- Seasoned Coldmine Explorer (0.5H)(2P)(7D)(1A)
UPDATE `creature_template` SET `MinLevel`='66', `MaxLevel`='67', `SpeedWalk` = 1 WHERE `entry` = 22751; -- Seasoned Coldmine Explorer (1)
UPDATE `creature_template` SET `MinLevel`='58', `MaxLevel`='59', `PowerMultiplier`='2', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13547'; -- Veteran Coldmine Explorer (0.6H)(1P)(2D)(1A)
UPDATE `creature_template` SET `SpeedWalk` = 1 WHERE `entry` = 22770; -- Veteran Coldmine Explorer (1)
UPDATE `creature_template` SET `MinLevel`='60', `MaxLevel`='60', `PowerMultiplier`='2', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `MechanicImmuneMask`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13548'; -- Champion Coldmine Explorer (0.7H)(1P)(3D)(1A)
UPDATE `creature_template` SET `SpeedWalk` = 1 WHERE `entry` = 22529; -- Champion Coldmine Explorer (1)
UPDATE `creature_template` SET `MinLevel`='56', `MaxLevel`='57', `DamageMultiplier`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13555'; -- Seasoned Irondeep Surveyor (0.5H)(2P)(1.5D)(1A)
UPDATE `creature_template` SET `MinLevel`='66', `MaxLevel`='67', `SpeedWalk` = 1 WHERE `entry` = 22758; -- Seasoned Irondeep Surveyor (1)
UPDATE `creature_template` SET `MinLevel`='58', `MaxLevel`='59', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13556'; -- Veteran Irondeep Surveyor (0.6H)(2P)(1D)(1A)
UPDATE `creature_template` SET `SpeedWalk` = 1 WHERE `entry` = 22777; -- Veteran Irondeep Surveyor (1)
UPDATE `creature_template` SET `MinLevel`='60', `MaxLevel`='60', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `MechanicImmuneMask`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13557'; -- Champion Irondeep Surveyor (0.7H)(2P)(3D)(1A)
UPDATE `creature_template` SET `MinLevel`='70', `MaxLevel`='70', `SpeedWalk` = 1 WHERE `entry` = 22537; -- Veteran Irondeep Surveyor (1)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='13716'; -- Celebras the Redeemed (8H)(4P)(5D)(1A)
UPDATE `creature_template` SET `heroicentry` = 22790, `faction` = 37, `MinLevel`='57', `PowerMultiplier`='2.5', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `MechanicImmuneMask`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13956'; -- Winterax Mystic (3H)(1P)(6D)(1A)
UPDATE `creature_template` SET `faction` = 37, `MinLevel`='67', `MaxLevel`='68', `expansion` = 0, `SpeedWalk` = 1, unitclass = 2 WHERE `entry` = 22790; -- Winterax Mystic (1)
UPDATE `creature_template` SET `heroicentry` = 22791, `faction` = 37, `PowerMultiplier`='2', `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `MechanicImmuneMask`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='13958'; -- Winterax Seer (3H)(1P)(6D)(1A)
UPDATE `creature_template` SET `faction` = 37, `MinLevel`='68', `MaxLevel`='69', `expansion` = 0, `SpeedWalk` = 1, unitclass = 2 WHERE `entry` = 22791; -- Winterax Seer (1)
UPDATE `creature_template` SET `faction` = 37, `MinLevel`='60', `MaxLevel`='60', `ExtraFlags`='0', `PowerMultiplier`='2', `ArmorMultiplier`='1', `MeleeBaseAttackTime`='2000', `MechanicImmuneMask`='1', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry`='14021'; -- Winterax Sentry (3H)(1P)(1D)(1.33333A) - faction might be 35
UPDATE `creature_template` SET `faction` = 37, `MinLevel`='70', `MaxLevel`='70', `ExtraFlags`='0', `expansion` = 0, `SpeedWalk` = 1 WHERE `entry` = 22599; -- Winterax Sentry (1)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MechanicImmuneMask`='1' WHERE `entry`='14385'; -- Doomguard Minion (1.5H)(0.77P)(2D)(1A)
UPDATE `creature_template` SET `faction` = 7 WHERE `entry`='14452'; -- Enslaved Doomguard Commander (20H)(5P)(9D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `MeleeBaseAttackTime`='2000', `SpeedWalk` = 1 WHERE `entry`='14533'; -- Simone the Seductress (5H)(5P)(1.27D)(1A)
UPDATE `creature_template` SET `ExtraFlags`='32768', `DamageMultiplier`='1', `SpeedWalk` = 1 WHERE `entry`='14639'; -- Zapped Deep Strider (1.25H)(1P)(0.8D)(1A) - 5360
UPDATE `creature_template` SET `ExtraFlags`='32768' where entry = 5360;
UPDATE `creature_template` SET `DamageMultiplier`='7.5' WHERE `entry`='14693'; -- Scorn (8H)(6P)(10D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', faction = 1555, unitflags = 832 WHERE `entry`='14865'; -- Felinni (3H)(1P)(2D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', faction = 1555, unitflags = 768 WHERE `entry`='14868'; -- Hornsley (1H)(1P)(0.7D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', faction = 1555, unitflags = 768 WHERE `entry`='14871'; -- Morja (1H)(1P)(0.7D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='10', `DamageMultiplier`='7.5' WHERE `entry`='14877'; -- High Priest Venoxis Transform Visual (70H)(1P)(1D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='10', `DamageMultiplier`='35', `MechanicImmuneMask`='12584977' WHERE `entry`='14941'; -- High Priestess Jeklik Transform Visual (150H)(1P)(1D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='3', `DamageMultiplier`='7.5' WHERE `entry`='14968'; -- High Priestess Arlokk Transform Visual (3H)(1P)(1D)(1A)
UPDATE `creature_template` SET `ExtraFlags`='66', `ArmorMultiplier`='1' WHERE `entry`='15061'; -- Spirit of Jin'do (1.2H)(1P)(1D)(1.33333A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `SkinningLootId`='0' WHERE `entry`='15193'; -- The Banshee Queen (300H)(20P)(0.1D)(1A)
UPDATE `creature_template` SET `InhabitType`='3', `ExtraFlags`='67', `DamageMultiplier`='1' WHERE `entry`='15362'; -- Malfurion Stormrage (500H)(500P)(7D)(1A)
UPDATE `creature_template` SET `ExtraFlags`='67' WHERE `entry`='15381'; -- Anachronos the Ancient (600H)(30P)(54D)(1A)
UPDATE `creature_template` SET `ExtraFlags`='67' WHERE `entry`='15382'; -- Fandral Staghelm (300H)(20P)(6D)(1A)
UPDATE `creature_template` SET `MinLevel`='63', `MaxLevel`='63', `ExtraFlags`='67', `PowerMultiplier`='30', `DamageMultiplier`='35' WHERE `entry`='15410'; -- Anachronos Dragon Form (600H)(1P)(1D)(1A)
UPDATE `creature_template` SET `MinLevel`='63', `MaxLevel`='63', `PowerMultiplier`='30', `DamageMultiplier`='35' WHERE `entry`='15411'; -- Arygos Dragon Form (600H)(1P)(1D)(1A)
UPDATE `creature_template` SET `MinLevel`='63', `MaxLevel`='63', `PowerMultiplier`='30', `DamageMultiplier`='35' WHERE `entry`='15412'; -- Caelestrasz Dragon Form (600H)(1P)(1D)(1A)
UPDATE `creature_template` SET `MinLevel`='63', `MaxLevel`='63', `PowerMultiplier`='30', `DamageMultiplier`='35' WHERE `entry`='15413'; -- Merithra Dragon Form (600H)(1P)(1D)(1A)
UPDATE `creature_template` SET `DamageMultiplier` = 13 WHERE `entry`='15471'; -- Lieutenant General Andorov (7H)(15P)(1D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='180', `DamageMultiplier`='35', `MechanicImmuneMask`='12584976' WHERE `entry`='15507'; -- Buru the Gorger Transform Visual (250H)(1P)(1D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='15559'; -- Elder Highpeak (1.2H)(1P)(2D)(1A)
UPDATE `creature_template` SET `UnitFlags`='256', `DamageMultiplier`='1' WHERE `entry`='15561'; -- Elder Obsidian (1.2H)(1P)(2D)(1A)
UPDATE `creature_template` SET `UnitFlags`='256', `DamageMultiplier`='1' WHERE `entry`='15567'; -- Elder Ironband (1.2H)(1P)(2D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `ArmorMultiplier`='1' WHERE `entry`='15607'; -- Elder Farwhisper (1.2H)(1P)(3D)(2.4961A)
UPDATE `creature_template` SET `PowerMultiplier`='20', `MinLootGold`='3396', `MaxLootGold`='4180' WHERE `entry`='15744'; -- Imperial Qiraji Destroyer (75H)(1P)(5D)(1A)
UPDATE `creature_template` SET `MinLevel`='61', `MaxLevel`='61', `Faction`='21', `PowerMultiplier`='3', `DamageMultiplier`='7.5' WHERE `entry`='15772'; -- Christmas Darkmaster Gandling (20H)(1P)(1D)(1A)
UPDATE `creature_template` SET `MinLevel`='24', `DamageMultiplier`='1' WHERE `entry`='15847'; -- Might of Kalimdor Shaman (1H)(1P)(0.7D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='15855'; -- Tauren Rifleman (20H)(5P)(4D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1', `ArmorMultiplier`='1' WHERE `entry`='15856'; -- Tauren Primalist (25H)(15P)(4.5D)(5.85366A)
UPDATE `creature_template` SET `faction` = 777, `DamageMultiplier`='1' WHERE `entry`='15859'; -- Stormwind Archmage (15H)(50P)(2D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='15860'; -- Kaldorei Marksman (25H)(1P)(4D)(1A)
UPDATE `creature_template` SET `HealthMultiplier`='25', `PowerMultiplier`='15', `DamageMultiplier`='1.9', `ArmorMultiplier`='1' WHERE `entry`='15863'; -- Darkspear Shaman (20H)(1P)(1.9D)(0.811132A)
UPDATE `creature_template` SET `PowerMultiplier`='2' WHERE `entry`='15867'; -- Might of Kalimdor Archmage (3H)(1P)(1D)(1A)
UPDATE `creature_template` SET `MinLevel`='60', `MaxLevel`='60' WHERE `entry`='15869'; -- Malagav the Tactician (150H)(50P)(6D)(1A)
UPDATE `creature_template` SET `PowerMultiplier`='15' WHERE `entry`='16083'; -- Mor Grayhoof Transformation Visual (11H)(1P)(1D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='1' WHERE `entry`='16109'; -- Mara Rennick (1H)(1P)(2D)(1A)
UPDATE `creature_template` SET `MeleeBaseAttackTime`='2000' WHERE `entry`='16143'; -- Shadow of Doom (20H)(1P)(13D)(1A)
UPDATE `creature_template` SET `NpcFlags`='0', `ExtraFlags`='2', `PowerMultiplier`='2', `DamageMultiplier`='7.5' WHERE `entry`='16439'; -- Fairbanks Transformed (5H)(1P)(1D)(1A)
UPDATE `creature_template` SET `DamageMultiplier`='26' WHERE `entry`='16452'; -- Necro Knight Guardian (25H)(18P)(42.5D)(1A)
UPDATE `creature_template` SET `ExtraFlags`='66', `DamageMultiplier`='1' WHERE `entry`='16478'; -- Lieutenant Orrin (1H)(1P)(3D)(1A)
UPDATE `creature_template` SET `NpcFlags`='2', `ArmorMultiplier`='1', unitflags = 33536 WHERE `entry`='16484'; -- Lieutenant Nevell (1H)(1P)(1D)(1.33333A)
UPDATE `creature_template` SET `NpcFlags`='2', `ArmorMultiplier`='1', unitflags = 33536 WHERE `entry`='16490'; -- Lieutenant Lisande (1H)(1P)(1D)(1.33333A)
UPDATE `creature_template` SET `NpcFlags`='2', `ArmorMultiplier`='1', unitflags = 33536 WHERE `entry`='16493'; -- Lieutenant Dagel (1H)(1P)(1D)(1.33333A)
UPDATE `creature_template` SET `NpcFlags`='2', `DamageMultiplier`='1', unitflags = 33536 WHERE `entry`='16494'; -- Lieutenant Rukag (1H)(1P)(3D)(1A)
UPDATE `creature_template` SET `NpcFlags`='2', `ArmorMultiplier`='1', unitflags = 33536 WHERE `entry`='16495'; -- Lieutenant Beitha (1H)(1P)(1D)(1.33333A)
UPDATE `creature_template` SET `DamageMultiplier`='60' WHERE `entry`='16505'; -- Naxxramas Follower (45H)(10P)(100D)(1A)

-- tbcbruteforce diff (219)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='1760'; -- Warrior (TEST) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='3580'; -- Crafticus Rabbitus (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='15349'; -- RC Blimp <PH> (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='15491'; -- Eranikus, Tyrant of the Dream (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='15646'; -- [Unused] Mana Leech (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='15947'; -- Whisperwind Villager (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16265'; -- Smith Daelarin (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16557'; -- Orc Warlock UNUSED (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16560'; -- Orc Necrolyte UNUSED (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16571'; -- Human Cleric UNUSED (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16572'; -- Human Conjurer UNUSED (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16581'; -- King Llane UNUSED (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16614'; -- Lothene (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16622'; -- Ithene (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16630'; -- Irodalmin (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16645'; -- Ithren (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16661'; -- Gez'li (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16682'; -- Thiel (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16702'; -- Telia (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16711'; -- Herman Walker (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16717'; -- Exodar Clothes Vendor (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16720'; -- Oktan (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16730'; -- Exodar Fireworks Vendor (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16758'; -- Jahri (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='16770'; -- Exodar Warlock Trainer (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16849'; -- Vindicator Xannar (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16853'; -- Anterius Black (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='16872'; -- Bleeding Hollow Warlock (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17064'; -- Night Mistress Transform Visual (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17091'; -- Mirren Longbeard No Hat (DND) (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17118'; -- Der'izu Arcanist (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17162'; -- Wretched Magistrix Elosai (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17168'; -- Shade of Aran Teleport N (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17169'; -- Shade of Aran Teleport S (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17170'; -- Shade of Aran Teleport E (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17171'; -- Shade of Aran Teleport W (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17172'; -- Shade of Aran Teleport NE (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17173'; -- Shade of Aran Teleport SE (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17174'; -- Shade of Aran Teleport SW (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17175'; -- Shade of Aran Teleport NW (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17176'; -- Shade of Aran Teleport Center (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17227'; -- Human Peasant (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17354'; -- Deonysius (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17383'; -- Honor Hold Marksman (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17388'; -- Orlug'Gonn (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17449'; -- Grisel (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17450'; -- Griselda (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17463'; -- [UNUSED] Shadowmoon Firestarter (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17515'; -- Samantha LeCraft (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17568'; -- Outland Doomguard (Default) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17569'; -- Outland Doomguard (Black) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17570'; -- Outland Doomguard (Blue) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17571'; -- Outland Doomguard (Green) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17572'; -- Outland Doomguard (Purple) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17573'; -- Outland Doomguard (Yellow) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17575'; -- Eric Maloof Test Critter (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17605'; -- Sunhawk Defiler (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17648'; -- Felhunter Minion (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17675'; -- Facet of Keanna (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17700'; -- Will of Sargaras (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='17868'; -- Silithus Spice Worm Mortar Target (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17949'; -- Malfurion Stormrage (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='17970'; -- Stormcrow Shape (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18045'; -- Rajah Kaz'sith (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18047'; -- Rajah Vethag (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18061'; -- Felguard Netherstorm (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18126'; -- Expedition Scout (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18169'; -- Blood Knight Initiate (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18194'; -- Expedition Preserver (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18269'; -- Khoraazi (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18270'; -- Kruugall (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='18329'; -- [UNUSED] Sethekk Magelord (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18367'; -- [UNUSED] Draenei Spirit [PH] (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='18599'; -- Exodar Aura Emitter (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18766'; -- Pool of Souls (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18769'; -- Young Thrall (Equipped) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18780'; -- The Curator Transform Visual (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='18819'; -- Exodar Proselyte Leader (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='18820'; -- Exodar Proselyte Leader 2 (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18845'; -- Benevolent Mr. Pinchy (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18888'; -- Peoreth of the Weakest Sauce (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='18889'; -- Maltrake, Servant of Rommath (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='18920'; -- Alorii (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19036'; -- Tun'Aakei (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19037'; -- Erath (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19039'; -- Fald'Erei (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19040'; -- Wahten (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19160'; -- Wrathguard Defender (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19199'; -- Dread Overseer (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19247'; -- Nuolla Dawncaller (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19260'; -- Destroyed Fel Reaver (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19262'; -- Dreadcaller Ebuch'nizor (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19313'; -- Dan Reed Magical Reflection Dummy (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19323'; -- Dan Reed Uber-resist Test Dummy (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19334'; -- Dreadcaller Xaldonus (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19552'; -- Goblin Zeppelin (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19556'; -- Thrall (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19577'; -- Arcane Orb Target (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19597'; -- Thrall's Hero Music (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19603'; -- Tauren Shaman (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19604'; -- Drek'Thar (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19647'; -- Thrall (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19696'; -- Polean (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='19700'; -- Johnny Castle (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19721'; -- Haris Nachosis (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19842'; -- Invis KV Defender (1C)
UPDATE `creature_template` SET `UnitClass`='1' WHERE `entry`='19850'; -- Councilor Arial D'Anastasis (8C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='19967'; -- Terror Sentry (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20000'; -- Kanrethad (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20144'; -- Magister Hathris (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20297'; -- Nova Terra (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20356'; -- Willey (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20364'; -- Darla Harris OH (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20366'; -- Darren Malvew OH (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20367'; -- Robby Aebischer (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='20369'; -- Loreseeker Dibbs (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20371'; -- Wesley OH (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20375'; -- Neema OH (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20423'; -- Kel'Thuzad (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20434'; -- Horse (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='20733'; -- Walla's Damage Dealer (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='20991'; -- Invis Dome Caster (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21031'; -- [PH] Arcane Guardian (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21143'; -- Legion Prototype Cannon 1 (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21144'; -- Legion Prototype Cannon 2 (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21146'; -- Legion Prototype Cannon 2 & 3 Felguard (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21149'; -- Legion Prototype Cannon 4 (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21150'; -- Legion Prototype Cannon 3 (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21219'; -- Coilfang Warlock (UNUSED) (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='21243'; -- Designer Island Gnome Emote [PH] (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='21278'; -- Designer Island Gnome Caster [PH] (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21297'; -- Invis Invisibility Caster (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21418'; -- Invis Infernal Target (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21464'; -- Ethereal Construct (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21658'; -- [UNUSED]Death's Deliverer (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21785'; -- Underbog Quaker (UNUSED) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21830'; -- Beholder (beige) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21831'; -- Beholder (blue) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21832'; -- Beholder (black) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21833'; -- Beholder (gray) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21834'; -- Beholder (green) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21835'; -- Beholder (red) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21836'; -- Beholder (spittle) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21972'; -- Shadowy Disguise Male Transform (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='21973'; -- Shadowy Disguise Female Transform (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='22010'; -- Cask (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22197'; -- Dragonmaw Orc (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='22210'; -- Priestess Spirit (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22409'; -- ZZZ - Dan Reed Test (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22425'; -- Evergrove Druid (Transform: Druid) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22426'; -- Evergrove Druid (Transform: Crow) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22473'; -- Baron Sablemane (8C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='22817'; -- Blood Elf Orphan (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22818'; -- Draenei Orphan (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22865'; -- Illidan's Presence (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22870'; -- Olum's Spirit (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22901'; -- Clintar's Spirit (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='22904'; -- Eye of Illidan (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23043'; -- Invis Guardian Caster (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23046'; -- Invis Raven God Portal (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23057'; -- Invis Raven God Target (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23058'; -- Invis Raven God Caster (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23075'; -- Legion Ring Infernal (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23104'; -- Bogblossom Bunny (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='23105'; -- Fel Imp Minion Transform (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23126'; -- [UNUSED] Boss Teron Gorefiend (Mounted) (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23227'; -- Eye of Shartuul Transform (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23240'; -- Invis Rizzle Grenade Chucker (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='23279'; -- Portable Fel Cannon Transform (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23321'; -- Dragonmaw Flight Instructor (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23331'; -- Ray Morningstar (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23505'; -- Tikas (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23509'; -- Spirit of the Past (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23526'; -- BurkeTest01 (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23588'; -- Riding Ram (Brewfest) (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='23722'; -- Sasha Goens (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23800'; -- Headless Horseman, Unhorsed (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23811'; -- Captured Totem (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='23893'; -- Invis Lighthouse Light (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='23910'; -- Mr. Pinchy (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24368'; -- Swift Riding Ram (Brewfest) (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='24430'; -- Sunseeker Channeler Image (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24693'; -- [UNUSED] Arcane Nightmare (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24695'; -- [UNUSED] Nether Shade (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24699'; -- [UNUSED] Sargeron Trickster (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24700'; -- Headless Horseman, friendly (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24964'; -- Shattered Sun Scout (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24984'; -- Christmas Grand Warlock Nethekurse (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24985'; -- Christmas Grandmaster Vorpil (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24986'; -- Christmas Exarch Maladaar (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24987'; -- Christmas Captain Skarloc (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24988'; -- Christmas Nethermancer Sepethrea (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='24990'; -- Christmas High Botanist Freywinn (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25004'; -- Emissary of Despair (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25005'; -- Emissary of Dread (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25041'; -- Felmyst Visual (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='25139'; -- [PH] Bri's Test NPC (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25344'; -- Seer Cragh Grimtusk (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25345'; -- Earthen Ring Horde Disguise (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25346'; -- Twilight Spy Viktor (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25347'; -- Vision of Nobundo (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25348'; -- Vision of Thrall (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25360'; -- Earthen Ring Alliance Disguise (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='25499'; -- PattyMacks Dummy (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25735'; -- Armageddon Target (1C)
UPDATE `creature_template` SET `UnitClass`='1' WHERE `entry`='25754'; -- Earthen Ring Flamecaller (2C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='25882'; -- Multiphase Disturbance (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='26042'; -- Twilight Midsummer Male Disguise (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='26089'; -- Kayri (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='26116'; -- Frostwave Lieutenant (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='26177'; -- 2.4 Sunwell 5 Man Tradeskill Bunny [PH] (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='26178'; -- Hailstone Lieutenant (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='26302'; -- Enchantments Vendor (1C)
UPDATE `creature_template` SET `UnitClass`='8' WHERE `entry`='26367'; -- Teleporter (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='26438'; -- Tranquil Air Spirit (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='27166'; -- The Brewmaiden (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='27169'; -- The Black Brewmaiden (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='27914'; -- Ethereal Soul-Trader (1C)
UPDATE `creature_template` SET `UnitClass`='2' WHERE `entry`='27936'; -- Pumpkin Soldier (1C)

