-- =====================================================
-- INCREASE TOTAL NUMBER OF SPAWNS FOR MINERALS IN ZONES - CURRENT VALUES ARE A LITTLE TOO LEAN RIGHT NOW
-- =====================================================
-- (`entry`, `max_limit`, `description`) values('2000','7','Master Mineral Pool - Alterac Mountains (Inner Section)');
UPDATE pool_template SET max_limit=12 WHERE entry=2000;
-- (`entry`, `max_limit`, `description`) values('2001','4','Master Mineral Pool - Alterac Mountains (Outer Section)');
UPDATE pool_template SET max_limit=8 WHERE entry=2001;
-- (`entry`, `max_limit`, `description`) values('2002','10','Master Mineral Pool - Arathi Highlands (Main Section)');
UPDATE pool_template SET max_limit=15 WHERE entry=2002;
-- (`entry`, `max_limit`, `description`) values('2003','4','Master Mineral Pool - Arathi Highlands (Drywhisker Gorge)');
UPDATE pool_template SET max_limit=4 WHERE entry=2003;
-- (`entry`, `max_limit`, `description`) values('2004','9','Master Mineral Pool - Badlands');
UPDATE pool_template SET max_limit=14 WHERE entry=2004;
-- (`entry`, `max_limit`, `description`) values('2005','8','Master Mineral Pool - Blasted Lands');
UPDATE pool_template SET max_limit=13 WHERE entry=2005;
-- (`entry`, `max_limit`, `description`) values('2006','4','Master Mineral Pool - Blasted Lands (Garrison Armory) - Special Mineral GOs ONLY');
UPDATE pool_template SET max_limit=4 WHERE entry=2006;
-- (`entry`, `max_limit`, `description`) values('2007','10','Master Mineral Pool - Burning Steppes');
UPDATE pool_template SET max_limit=15 WHERE entry=2007;
-- (`entry`, `max_limit`, `description`) values('2008','12','Master Mineral Pool - Dun Morogh');
UPDATE pool_template SET max_limit=17 WHERE entry=2008;
-- (`entry`, `max_limit`, `description`) values('2009','16','Master Mineral Pool - Duskwood');
UPDATE pool_template SET max_limit=21 WHERE entry=2009;
-- (`entry`, `max_limit`, `description`) values('2010','13','Master Mineral Pool - Eastern Plaguelands');
UPDATE pool_template SET max_limit=18 WHERE entry=2010;
-- (`entry`, `max_limit`, `description`) values('2011','13','Master Mineral Pool - Elwynn Forest');
UPDATE pool_template SET max_limit=18 WHERE entry=2011;
-- (`entry`, `max_limit`, `description`) values('2012','6','Master Mineral Pool - Eversong Woods');
UPDATE pool_template SET max_limit=11 WHERE entry=2012;
-- (`entry`, `max_limit`, `description`) values('2013','9','Master Mineral Pool - Ghostlands');
UPDATE pool_template SET max_limit=14 WHERE entry=2013;
-- (`entry`, `max_limit`, `description`) values('2014','5','Master Mineral Pool - Hillsbrad Foothills (Main Section)');
UPDATE pool_template SET max_limit=10 WHERE entry=2014;
-- (`entry`, `max_limit`, `description`) values('2015','5','Master Mineral Pool - Hillsbrad Foothills (Higher Level Sections)');
UPDATE pool_template SET max_limit=10 WHERE entry=2015;
-- (`entry`, `max_limit`, `description`) values('2016','4','Master Mineral Pool - Hillsbrad Foothills (Azurelode Mine) - Special Mineral GOs ONLY');
UPDATE pool_template SET max_limit=4 WHERE entry=2016;
-- (`entry`, `max_limit`, `description`) values('2017','2','Master Mineral Pool - Isle of Quel\'Danas');
UPDATE pool_template SET max_limit=2 WHERE entry=2017;
-- (`entry`, `max_limit`, `description`) values('2018','9','Master Mineral Pool - Loch Modan');
UPDATE pool_template SET max_limit=14 WHERE entry=2018;
-- (`entry`, `max_limit`, `description`) values('2019','9','Master Mineral Pool - Redridge Mountians (Main Section)');
UPDATE pool_template SET max_limit=14 WHERE entry=2019;
-- (`entry`, `max_limit`, `description`) values('2020','4','Master Mineral Pool - Redridge Mountians (Rethban Caverns)');
UPDATE pool_template SET max_limit=4 WHERE entry=2020;
-- (`entry`, `max_limit`, `description`) values('2021','7','Master Mineral Pool - Searing Gorge (West Section)');
UPDATE pool_template SET max_limit=12 WHERE entry=2021;
-- (`entry`, `max_limit`, `description`) values('2022','5','Master Mineral Pool - Searing Gorge (East Section)');
UPDATE pool_template SET max_limit=10 WHERE entry=2022;
-- (`entry`, `max_limit`, `description`) values('2023','7','Master Mineral Pool - Silverpine Forest');
UPDATE pool_template SET max_limit=12 WHERE entry=2023;
-- (`entry`, `max_limit`, `description`) values('2024','11','Master Mineral Pool - Stranglethorn Vale');
UPDATE pool_template SET max_limit=18 WHERE entry=2024;
-- (`entry`, `max_limit`, `description`) values('2025','9','Master Mineral Pool - Swamp of Sorrows');
UPDATE pool_template SET max_limit=14 WHERE entry=2025;
-- (`entry`, `max_limit`, `description`) values('2026','7','Master Mineral Pool - The Hinterlands');
UPDATE pool_template SET max_limit=12 WHERE entry=2026;
-- (`entry`, `max_limit`, `description`) values('2027','7','Master Mineral Pool - Tirisfal Glades');
UPDATE pool_template SET max_limit=12 WHERE entry=2027;
-- (`entry`, `max_limit`, `description`) values('2028','5','Master Mineral Pool - Western Plaguelands (South-West Section)');
UPDATE pool_template SET max_limit=10 WHERE entry=2028;
-- (`entry`, `max_limit`, `description`) values('2029','4','Master Mineral Pool - Western Plaguelands (East and North Sections)');
UPDATE pool_template SET max_limit=8 WHERE entry=2029;
-- (`entry`, `max_limit`, `description`) values('2030','8','Master Mineral Pool - Westfall');
UPDATE pool_template SET max_limit=13 WHERE entry=2030;
-- (`entry`, `max_limit`, `description`) values('2031','7','Master Mineral Pool - Wetlands (Main Section)');
UPDATE pool_template SET max_limit=12 WHERE entry=2031;
-- (`entry`, `max_limit`, `description`) values('2032','4','Master Mineral Pool - Wetlands (Thelgen Rock)');
UPDATE pool_template SET max_limit=4 WHERE entry=2032;
-- (`entry`, `max_limit`, `description`) values('2033','8','Master Mineral Pool - Ashenvale (West Section)');
UPDATE pool_template SET max_limit=13 WHERE entry=2033;
-- (`entry`, `max_limit`, `description`) values('2034','8','Master Mineral Pool - Ashenvale (East Section)');
UPDATE pool_template SET max_limit=13 WHERE entry=2034;
-- (`entry`, `max_limit`, `description`) values('2035','11','Master Mineral Pool - Azshara');
UPDATE pool_template SET max_limit=16 WHERE entry=2035;
-- (`entry`, `max_limit`, `description`) values('2036','11','Master Mineral Pool - Azuremyst Isle');
UPDATE pool_template SET max_limit=16 WHERE entry=2036;
-- (`entry`, `max_limit`, `description`) values('2037','3','Master Mineral Pool - Bloodmyst Isle (Lower Level Section)');
UPDATE pool_template SET max_limit=5 WHERE entry=2037;
-- (`entry`, `max_limit`, `description`) values('2038','9','Master Mineral Pool - Bloodmyst Isle (Main Section)');
UPDATE pool_template SET max_limit=14 WHERE entry=2038;
-- (`entry`, `max_limit`, `description`) values('2039','12','Master Mineral Pool - Darkshore');
UPDATE pool_template SET max_limit=17 WHERE entry=2039;
-- (`entry`, `max_limit`, `description`) values('2040','9','Master Mineral Pool - Desolace');
UPDATE pool_template SET max_limit=14 WHERE entry=2040;
-- (`entry`, `max_limit`, `description`) values('2041','13','Master Mineral Pool - Durotar');
UPDATE pool_template SET max_limit=18 WHERE entry=2041;
-- (`entry`, `max_limit`, `description`) values('2042','9','Master Mineral Pool - Dustwallow Marsh');
UPDATE pool_template SET max_limit=14 WHERE entry=2042;
-- (`entry`, `max_limit`, `description`) values('2043','9','Master Mineral Pool - Felwood');
UPDATE pool_template SET max_limit=14 WHERE entry=2043;
-- (`entry`, `max_limit`, `description`) values('2045','7','Master Mineral Pool - Feralas');
UPDATE pool_template SET max_limit=12 WHERE entry=2045;
-- (`entry`, `max_limit`, `description`) values('2046','4','Master Mineral Pool - Feralas (Ooze Covered Mineral GOs)');
UPDATE pool_template SET max_limit=4 WHERE entry=2046;
-- (`entry`, `max_limit`, `description`) values('2047','11','Master Mineral Pool - Mulgore');
UPDATE pool_template SET max_limit=16 WHERE entry=2047;
-- (`entry`, `max_limit`, `description`) values('2048','7','Master Mineral Pool - Silithus');
UPDATE pool_template SET max_limit=12 WHERE entry=2048;
-- (`entry`, `max_limit`, `description`) values('2049','8','Master Mineral Pool - Silithus (Ooze Covered Mineral GOs)');
UPDATE pool_template SET max_limit=13 WHERE entry=2049;
-- (`entry`, `max_limit`, `description`) values('2050','7','Master Mineral Pool - Stonetalon Mountians');
UPDATE pool_template SET max_limit=12 WHERE entry=2050;
-- (`entry`, `max_limit`, `description`) values('2051','9','Master Mineral Pool - Tanaris');
UPDATE pool_template SET max_limit=14 WHERE entry=2051;
-- (`entry`, `max_limit`, `description`) values('2052','13','Master Mineral Pool - The Barrens (Main Section)');
UPDATE pool_template SET max_limit=21 WHERE entry=2052;
-- (`entry`, `max_limit`, `description`) values('2053','3','Master Mineral Pool - The Barrens (Bael Modan)');
UPDATE pool_template SET max_limit=3 WHERE entry=2053;
-- (`entry`, `max_limit`, `description`) values('2055','13','Master Mineral Pool - Thousand Needles');
UPDATE pool_template SET max_limit=18 WHERE entry=2055;
-- (`entry`, `max_limit`, `description`) values('2056','3','Master Mineral Pool - Thousand Needles (Ooze Covered Mineral GOs)');
UPDATE pool_template SET max_limit=3 WHERE entry=2056;
-- (`entry`, `max_limit`, `description`) values('2057','1','Master Mineral Pool - Thunder Bluff');
UPDATE pool_template SET max_limit=12 WHERE entry=2057;
-- (`entry`, `max_limit`, `description`) values('2058','11','Master Mineral Pool - Un\'Goro Crater');
UPDATE pool_template SET max_limit=16 WHERE entry=2058;
-- (`entry`, `max_limit`, `description`) values('2059','5','Master Mineral Pool - Un\'Goro Crater (Ooze Covered Mineral GOs)');
UPDATE pool_template SET max_limit=5 WHERE entry=2059;
-- (`entry`, `max_limit`, `description`) values('2060','7','Master Mineral Pool - Winterspring (Main Section)');
UPDATE pool_template SET max_limit=12 WHERE entry=2060;
-- (`entry`, `max_limit`, `description`) values('2061','5','Master Mineral Pool - Winterspring (West Section)');
UPDATE pool_template SET max_limit=10 WHERE entry=2061;
-- (`entry`, `max_limit`, `description`) values('2062','25','Master Mineral Pool - Hellfire Peninsula');
UPDATE pool_template SET max_limit=25 WHERE entry=2062;
-- (`entry`, `max_limit`, `description`) values('2063','25','Master Mineral Pool - Zangarmarsh');
UPDATE pool_template SET max_limit=25 WHERE entry=2063;
-- (`entry`, `max_limit`, `description`) values('2064','25','Master Mineral Pool - Nagrand');
UPDATE pool_template SET max_limit=25 WHERE entry=2064;
-- (`entry`, `max_limit`, `description`) values('2065','25','Master Mineral Pool - Terokkar Forest');
UPDATE pool_template SET max_limit=25 WHERE entry=2065;
-- (`entry`, `max_limit`, `description`) values('2066','25','Master Mineral Pool - Netherstorm');
UPDATE pool_template SET max_limit=25 WHERE entry=2066;
-- (`entry`, `max_limit`, `description`) values('2067','25','Master Mineral Pool - Blades Edge Mountains');
UPDATE pool_template SET max_limit=25 WHERE entry=2067;
-- (`entry`, `max_limit`, `description`) values('2068','25','Master Mineral Pool - Shadowmoon Valley');
UPDATE pool_template SET max_limit=25 WHERE entry=2068;
-- (`entry`, `max_limit`, `description`) values('2069','5','Master Mineral Pool - Shadowmoon Valley (Nethercite Spawns)');
UPDATE pool_template SET max_limit=5 WHERE entry=2069;



-- ==================================================
-- INCREASE TOTAL NUMBER OF SPAWNS FOR HERBS IN ZONES - CURRENT VALUES ARE A LITTLE TOO LEAN RIGHT NOW
-- ==================================================
-- (`entry`, `max_limit`, `description`) values('13000','12','Master Herb Pool - Alterac Mountains');
UPDATE pool_template SET max_limit=17 WHERE entry=13000;
-- (`entry`, `max_limit`, `description`) values('13001','15','Master Herb Pool - Arathi Highlands');
UPDATE pool_template SET max_limit=17 WHERE entry=13001;
-- (`entry`, `max_limit`, `description`) values('13002','11','Master Herb Pool - Badlands');
UPDATE pool_template SET max_limit=16 WHERE entry=13002;
-- (`entry`, `max_limit`, `description`) values('13003','12','Master Herb Pool - Blasted Lands');
UPDATE pool_template SET max_limit=17 WHERE entry=13003;
-- (`entry`, `max_limit`, `description`) values('13004','13','Master Herb Pool - Burning Steppes');
UPDATE pool_template SET max_limit=18 WHERE entry=13004;
-- (`entry`, `max_limit`, `description`) values('13005','13','Master Herb Pool - Dun Morogh');
UPDATE pool_template SET max_limit=18 WHERE entry=13005;
-- (`entry`, `max_limit`, `description`) values('13006','14','Master Herb Pool - Duskwood');
UPDATE pool_template SET max_limit=19 WHERE entry=13006;
-- (`entry`, `max_limit`, `description`) values('13007','15','Master Herb Pool - Eastern Plaguelands');
UPDATE pool_template SET max_limit=18 WHERE entry=13007;
-- (`entry`, `max_limit`, `description`) values('13008','14','Master Herb Pool - Elwynn Forest');
UPDATE pool_template SET max_limit=18 WHERE entry=13008;
-- (`entry`, `max_limit`, `description`) values('13009','14','Master Herb Pool - Eversong Woods');
UPDATE pool_template SET max_limit=18 WHERE entry=13009;
-- (`entry`, `max_limit`, `description`) values('13010','11','Master Herb Pool - Ghostlands');
UPDATE pool_template SET max_limit=16 WHERE entry=13010;
-- (`entry`, `max_limit`, `description`) values('13011','13','Master Herb Pool - Hillsbrad Foothills');
UPDATE pool_template SET max_limit=18 WHERE entry=13011;
-- (`entry`, `max_limit`, `description`) values('13012','2','Master Herb Pool - Isle of Quel\'Danas');
UPDATE pool_template SET max_limit=2 WHERE entry=13012;
-- (`entry`, `max_limit`, `description`) values('13013','14','Master Herb Pool - Loch Modan');
UPDATE pool_template SET max_limit=18 WHERE entry=13013;
-- (`entry`, `max_limit`, `description`) values('13014','13','Master Herb Pool - Redridge Mountains');
UPDATE pool_template SET max_limit=18 WHERE entry=13014;
-- (`entry`, `max_limit`, `description`) values('13015','10','Master Herb Pool - Searing Gorge');
UPDATE pool_template SET max_limit=14 WHERE entry=13015;
-- (`entry`, `max_limit`, `description`) values('13016','13','Master Herb Pool - Silverpine Forest');
UPDATE pool_template SET max_limit=18 WHERE entry=13016;
-- (`entry`, `max_limit`, `description`) values('13017','20','Master Herb Pool - Stranglethorn Vale');
UPDATE pool_template SET max_limit=23 WHERE entry=13017;
-- (`entry`, `max_limit`, `description`) values('13018','12','Master Herb Pool - Swamp of Sorrows');
UPDATE pool_template SET max_limit=17 WHERE entry=13018;
-- (`entry`, `max_limit`, `description`) values('13019','14','Master Herb Pool - The Hinterlands');
UPDATE pool_template SET max_limit=17 WHERE entry=13019;
-- (`entry`, `max_limit`, `description`) values('13020','11','Master Herb Pool - Tirisfal Glades');
UPDATE pool_template SET max_limit=16 WHERE entry=13020;
-- (`entry`, `max_limit`, `description`) values('13021','13','Master Herb Pool - Western Plaguelands');
UPDATE pool_template SET max_limit=18 WHERE entry=13021;
-- (`entry`, `max_limit`, `description`) values('13022','13','Master Herb Pool - Westfall');
UPDATE pool_template SET max_limit=18 WHERE entry=13022;
-- (`entry`, `max_limit`, `description`) values('13023','13','Master Herb Pool - Wetlands');
UPDATE pool_template SET max_limit=17 WHERE entry=13023;
-- (`entry`, `max_limit`, `description`) values('13024','14','Master Herb Pool - Ashenvale');
UPDATE pool_template SET max_limit=18 WHERE entry=13024;
-- (`entry`, `max_limit`, `description`) values('13025','13','Master Herb Pool - Azshara');
UPDATE pool_template SET max_limit=17 WHERE entry=13025;
-- (`entry`, `max_limit`, `description`) values('13026','10','Master Herb Pool - Azuremyst Isle');
UPDATE pool_template SET max_limit=16 WHERE entry=13026;
-- (`entry`, `max_limit`, `description`) values('13027','10','Master Herb Pool - Bloodmyst Isle');
UPDATE pool_template SET max_limit=15 WHERE entry=13027;
-- (`entry`, `max_limit`, `description`) values('13028','13','Master Herb Pool - Darkshore');
UPDATE pool_template SET max_limit=18 WHERE entry=13028;
-- (`entry`, `max_limit`, `description`) values('13029','12','Master Herb Pool - Desolace');
UPDATE pool_template SET max_limit=16 WHERE entry=13029;
-- (`entry`, `max_limit`, `description`) values('13030','14','Master Herb Pool - Durotar');
UPDATE pool_template SET max_limit=18 WHERE entry=13030;
-- (`entry`, `max_limit`, `description`) values('13031','12','Master Herb Pool - Dustwallow Marsh');
UPDATE pool_template SET max_limit=16 WHERE entry=13031;
-- (`entry`, `max_limit`, `description`) values('13032','12','Master Herb Pool - Felwood');
UPDATE pool_template SET max_limit=16 WHERE entry=13032;
-- (`entry`, `max_limit`, `description`) values('13033','13','Master Herb Pool - Feralas');
UPDATE pool_template SET max_limit=17 WHERE entry=13033;
-- (`entry`, `max_limit`, `description`) values('13034','12','Master Herb Pool - Mulgore');
UPDATE pool_template SET max_limit=18 WHERE entry=13034;
-- (`entry`, `max_limit`, `description`) values('13035','10','Master Herb Pool - Silithus');
UPDATE pool_template SET max_limit=16 WHERE entry=13035;
-- (`entry`, `max_limit`, `description`) values('13036','12','Master Herb Pool - Stonetalon Mountians');
UPDATE pool_template SET max_limit=16 WHERE entry=13036;
-- (`entry`, `max_limit`, `description`) values('13037','10','Master Herb Pool - Tanaris');
UPDATE pool_template SET max_limit=15 WHERE entry=13037;
-- (`entry`, `max_limit`, `description`) values('13038','10','Master Herb Pool - Teldrassil');
UPDATE pool_template SET max_limit=16 WHERE entry=13038;
-- (`entry`, `max_limit`, `description`) values('13039','25','Master Herb Pool - The Barrens');
UPDATE pool_template SET max_limit=29 WHERE entry=13039;
-- (`entry`, `max_limit`, `description`) values('13040','11','Master Herb Pool - Thousand Needles');
UPDATE pool_template SET max_limit=15 WHERE entry=13040;
-- (`entry`, `max_limit`, `description`) values('13041','13','Master Herb Pool - Un\'Goro Crater');
UPDATE pool_template SET max_limit=17 WHERE entry=13041;
-- (`entry`, `max_limit`, `description`) values('13042','13','Master Herb Pool - Winterspring');
UPDATE pool_template SET max_limit=15 WHERE entry=13042;
-- (`entry`, `max_limit`, `description`) values('13043','12','Master Herb Pool - Blades Edge Mountains');
UPDATE pool_template SET max_limit=18 WHERE entry=13043;
-- (`entry`, `max_limit`, `description`) values('13044','14','Master Herb Pool - Hellfire Peninsula');
UPDATE pool_template SET max_limit=18 WHERE entry=13044;
-- (`entry`, `max_limit`, `description`) values('13045','12','Master Herb Pool - Nagrand');
UPDATE pool_template SET max_limit=18 WHERE entry=13045;
-- (`entry`, `max_limit`, `description`) values('13046','13','Master Herb Pool - Netherstorm');
UPDATE pool_template SET max_limit=18 WHERE entry=13046;
-- (`entry`, `max_limit`, `description`) values('13047','13','Master Herb Pool - Shadowmoon Valley');
UPDATE pool_template SET max_limit=18 WHERE entry=13047;
-- (`entry`, `max_limit`, `description`) values('13048','14','Master Herb Pool - Terokkar Forest');
UPDATE pool_template SET max_limit=18 WHERE entry=13048;
-- (`entry`, `max_limit`, `description`) values('13049','13','Master Herb Pool - Zangarmarsh');
UPDATE pool_template SET max_limit=18 WHERE entry=13049;













