UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_event JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_event JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_event JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_event JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscript_random_templates JOIN dbscript_string ON target_id=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET target_id=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

-- explicit updates from instance files
UPDATE broadcast_text SET SoundEntriesID1=5851, ChatTypeID=1 WHERE Id=3261;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=3882;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=3884;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=6067;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=5622;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=4984;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=4986;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=4987;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=4979;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=4980;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=4981;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=5 WHERE Id IN (19909,19911);
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=11408;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=8951;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14406;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id IN (9416,9424);
UPDATE broadcast_text SET EmoteID1=1 WHERE Id IN (9446,9447,9448);
UPDATE broadcast_text SET EmoteID1=4 WHERE Id=9346;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=9705;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=9348;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id IN (13806,13804,13252,13251,13828,13827,13826,13198,13201,13202,13204,13206,13805);
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=13302;
UPDATE broadcast_text SET EmoteID1=66 WHERE Id=13307;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=21646;
UPDATE broadcast_text SET EmoteID1=274 WHERE Id=21645;
UPDATE broadcast_text SET ChatTypeID=7 WHERE Id=15310;
UPDATE broadcast_text SET SoundEntriesID1=10191, ChatTypeID=1, EmoteID1=15 WHERE Id=16350;
UPDATE broadcast_text SET SoundEntriesID1=10190, ChatTypeID=1, EmoteID1=15 WHERE Id=17461;
UPDATE broadcast_text SET SoundEntriesID1=10189, ChatTypeID=1, EmoteID1=15 WHERE Id=16349;
UPDATE broadcast_text SET SoundEntriesID1=10188, ChatTypeID=1, EmoteID1=15 WHERE Id=16347;
UPDATE broadcast_text SET SoundEntriesID1=10187, ChatTypeID=1, EmoteID1=15 WHERE Id=16346;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id IN (12685,12686);
UPDATE broadcast_text SET EmoteID1=25 WHERE Id=12687;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=12684;
UPDATE broadcast_text SET EmoteID1=15 WHERE Id=12683;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=25 WHERE Id=13695;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=66 WHERE Id=13989;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id IN (18599,18600);
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15896;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id IN (18910,18909,18893,18888,18889,18891,18890,19344,18887,18892,18903,18905,18902,18904,18895,18897,18900,18898,18901,18894,18899,18896,17713,17711,18145,18146,18410,20460);
UPDATE broadcast_text SET EmoteID1=15 WHERE Id=18911;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id IN (17839,17840,17841,17818);
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=66 WHERE Id IN (18031,18040,18037,18032,18038,18035,18036,18030,18039,18047,18048,18049,18045,18046);
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=4 WHERE Id=16861;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id IN (17178,17000,16999);
UPDATE broadcast_text SET EmoteID1=69 WHERE Id IN (16945,16946,16948,16947);
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id IN (16993,16994);
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16056;
UPDATE broadcast_text SET SoundEntriesID1=10428, ChatTypeID=1, EmoteID1=25 WHERE Id=15737;
UPDATE broadcast_text SET SoundEntriesID1=6400, EmoteID1=71 WHERE Id=23208;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=25482;

DROP TABLE dbscript_string;

-- Changes to support creature_ai_texts removal:

UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=1 WHERE Id=601;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=1 WHERE Id=604;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=22 WHERE Id=619;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=621;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=623;
UPDATE broadcast_text SET EmoteID1=65 WHERE Id=626;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=773;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=841;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=907;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=1017;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=1079;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1080;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1191;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1234;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1327;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1409;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1410;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1521;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=1927;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=2231;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=2571;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5841 WHERE Id=2655;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=2848;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3131;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=3170;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3367;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3541;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3542;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3543;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=3689;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=3691;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=3692;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=3693;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4142;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4166;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4177;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4178;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4364;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5819 WHERE Id=4435;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5859 WHERE Id=4485;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5871 WHERE Id=4546;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4549;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4703;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4962;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4998;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=5547;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5548;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5594;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5614;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=5616;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5774 WHERE Id=5619;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=6596 WHERE Id=5773;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5788;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5780 WHERE Id=6061;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5781 WHERE Id=6062;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5782 WHERE Id=6063;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5783 WHERE Id=6064;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5784 WHERE Id=6065;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=6150;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5801 WHERE Id=6170;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5802 WHERE Id=6171;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5803 WHERE Id=6172;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5811 WHERE Id=6177;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5812 WHERE Id=6178;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5815 WHERE Id=6181;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5816 WHERE Id=6182;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5814 WHERE Id=6183;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5823 WHERE Id=6185;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5844 WHERE Id=6201;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5846 WHERE Id=6202;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5845 WHERE Id=6203;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5847 WHERE Id=6204;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5848 WHERE Id=6205;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5849 WHERE Id=6206;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5850 WHERE Id=6207;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5852 WHERE Id=6212;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5854 WHERE Id=6214;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5860 WHERE Id=6216;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5862 WHERE Id=6217;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5866 WHERE Id=6220;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5874 WHERE Id=6223;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5875 WHERE Id=6224;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5876 WHERE Id=6225;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5877 WHERE Id=6226;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5879 WHERE Id=6227;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5878 WHERE Id=6228;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=6504;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=6512;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=6530;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=7272;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=7979;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=8675;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=8888;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=8915;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=8916;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=9304;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9374;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9375;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9376;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=9407;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=9500;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=9572;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=8274 WHERE Id=9614;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=9658;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=9661;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=9662;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=9664;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=9666;
UPDATE broadcast_text SET ChatTypeID=7 WHERE Id=9668;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=9674;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=9676;
UPDATE broadcast_text SET ChatTypeID=7 WHERE Id=9679;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=9727;
UPDATE broadcast_text SET ChatTypeID=7 WHERE Id=9763;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=1 WHERE Id=9810;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=8272 WHERE Id=9958;
UPDATE broadcast_text SET ChatTypeID=6 WHERE Id=10009;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=10025;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10133;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10135;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10160;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=10755;
UPDATE broadcast_text SET SoundEntriesID1=8507 WHERE Id=10985;
UPDATE broadcast_text SET SoundEntriesID1=8506 WHERE Id=10986;
UPDATE broadcast_text SET EmoteID1=66 WHERE Id=10993;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10994;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=25 WHERE Id=11009;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=11270;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=8613 WHERE Id=11434;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=11700;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11727;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11770;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11860;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11861;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11873;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11966;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11967;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11970;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11971;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11972;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11973;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11974;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11975;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12521;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12627;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=12786;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=13398;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13413;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=18 WHERE Id=13414;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=13415;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=13418;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13420;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=13944;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10160 WHERE Id=14000;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14001;
UPDATE broadcast_text SET EmoteID1=71 WHERE Id=14077;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14322;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14366;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14414;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=14444;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14666;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15179;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15185;
UPDATE broadcast_text SET ChatTypeID=3 WHERE Id=15438;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15468;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15483;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15719;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=15941;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10421 WHERE Id=16023;
UPDATE broadcast_text SET EmoteID1=18 WHERE Id=16093;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16139;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16226;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16233;
UPDATE broadcast_text SET EmoteID1=24 WHERE Id=16328;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16331;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16332;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16333;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16334;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16335;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16336;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16337;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16338;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16339;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16340;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16351;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16368;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16369;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16370;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16371;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16372;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16373;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16374;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16378;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16379;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16381;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16387;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16429;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16437;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16475;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16557;
UPDATE broadcast_text SET ChatTypeID=2, SoundEntriesID1=6386, EmoteID1=5 WHERE Id=16580;
UPDATE broadcast_text SET ChatTypeID=2, SoundEntriesID1=6133, EmoteID1=5 WHERE Id=16581;
UPDATE broadcast_text SET ChatTypeID=2, SoundEntriesID1=9643, EmoteID1=5 WHERE Id=16582;
UPDATE broadcast_text SET ChatTypeID=2, SoundEntriesID1=6143, EmoteID1=5 WHERE Id=16583;
UPDATE broadcast_text SET ChatTypeID=2, SoundEntriesID1=6368, EmoteID1=5 WHERE Id=16584;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16587;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10429 WHERE Id=16650;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16651;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16652;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16653;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16655;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16656;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16657;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16658;
UPDATE broadcast_text SET EmoteID1=25 WHERE Id=16661;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10432 WHERE Id=16662;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10434 WHERE Id=16664;
UPDATE broadcast_text SET EmoteID1=25 WHERE Id=16665;
UPDATE broadcast_text SET EmoteID1=25 WHERE Id=16666;
UPDATE broadcast_text SET EmoteID1=25 WHERE Id=16667;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16668;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16669;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16670;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16671;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16672;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10407 WHERE Id=16673;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10409 WHERE Id=16675;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10411 WHERE Id=16677;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16678;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16679;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16680;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16681;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16682;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=16683;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10425 WHERE Id=16694;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10427 WHERE Id=16696;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16781;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16785;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16804;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16858;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16859;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16860;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=17004;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=17179;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=17180;
UPDATE broadcast_text SET EmoteID1=15 WHERE Id=17181;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17532;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=17571;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17593;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10530 WHERE Id=17641;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=17653;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=17654;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10376 WHERE Id=17888;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10380 WHERE Id=17892;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10382 WHERE Id=17894;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17923;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17924;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18602;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18606;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=5 WHERE Id=18708;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18712;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18714;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18715;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18719;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18869;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18998;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19207;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19300;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19308;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=19445;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11309 WHERE Id=19502;
UPDATE broadcast_text SET EmoteID1=25 WHERE Id=19504;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19506;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19577;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19621;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=53 WHERE Id=19846;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11071 WHERE Id=19936;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11073 WHERE Id=19938;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11079 WHERE Id=19942;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11306 WHERE Id=19993;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11114 WHERE Id=20030;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11110 WHERE Id=20031;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11109 WHERE Id=20033;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11101 WHERE Id=20034;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11102 WHERE Id=20035;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11106 WHERE Id=20039;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11250 WHERE Id=20045;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11251 WHERE Id=20046;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11255 WHERE Id=20050;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20136;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20137;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20140;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20366;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10986 WHERE Id=20432;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20565;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20745;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21366;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21902;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21905;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=22140;
UPDATE broadcast_text SET SoundEntriesID1=11797 WHERE Id=22167;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=22370;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=22371;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=22419;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23501;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23502;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23514;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23518;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=24175;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=24184;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=24192;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=1 WHERE Id=24205;

UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=1 WHERE Id=602;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=764;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5820 WHERE Id=4436;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5824 WHERE Id=6186;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=7274;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10134;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10135;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10155;
UPDATE broadcast_text SET EmoteID1=66 WHERE Id=10992;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=6 WHERE Id=12517;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=12787;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=2 WHERE Id=13417;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13419;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13422;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13423;
UPDATE broadcast_text SET EmoteID1=71 WHERE Id=14082;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14404;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15180;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15186;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=15942;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16097;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16138;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16228;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16235;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16343;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16386;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16648;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10433 WHERE Id=16663;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10408 WHERE Id=16674;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10410 WHERE Id=16676;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10422 WHERE Id=16693;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10426 WHERE Id=16695;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16784;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10531 WHERE Id=17642;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=17655;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10378 WHERE Id=17890;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10381 WHERE Id=17893;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=17913;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17922;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17924;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=5 WHERE Id=18710;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18711;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19299;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=19446;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11072 WHERE Id=19937;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11307 WHERE Id=19994;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11111 WHERE Id=20032;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11103 WHERE Id=20036;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11252 WHERE Id=20047;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20365;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=22139;
UPDATE broadcast_text SET SoundEntriesID1=11798 WHERE Id=22168;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23498;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23499;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23516;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23527;

UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=1 WHERE Id=603;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=778;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5821 WHERE Id=4437;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=7273;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10134;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10136;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=10155;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=2 WHERE Id=12514;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=18 WHERE Id=13416;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13421;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13424;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13425;
UPDATE broadcast_text SET EmoteID1=71 WHERE Id=14076;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14413;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15181;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15187;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16095;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16137;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16230;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16237;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16345;
UPDATE broadcast_text SET EmoteID1=6 WHERE Id=16389;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16390;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=17114;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10532 WHERE Id=17643;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10379 WHERE Id=17889;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10381 WHERE Id=17893;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17922;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17923;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=5 WHERE Id=18712;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=19444;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11308 WHERE Id=19995;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20368;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=22138;
UPDATE broadcast_text SET SoundEntriesID1=11796 WHERE Id=22166;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23497;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23500;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23513;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23515;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23517;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=23519;

UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=637;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=741;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=757;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=758;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=759;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=775;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1048;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1064;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1150;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1151;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1191;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1225;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1254;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1385;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1408;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1414;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2081;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2082;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2356;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2384;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=15 WHERE Id=2441;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2481;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3642;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3713;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4539;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4561;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4566;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4837;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4838;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5460;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5611;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5612;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5613;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5772;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=5951;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=6033;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5799 WHERE Id=6169;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5813 WHERE Id=6179;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5822 WHERE Id=6184;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5853 WHERE Id=6213;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5865 WHERE Id=6219;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=6257;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=6258;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=6511;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5864 WHERE Id=6538;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=8398;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=8619;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=8852;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9144;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9413;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9414;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9477;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=9478;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=8273 WHERE Id=9960;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=10549;
UPDATE broadcast_text SET SoundEntriesID1=8508 WHERE Id=10987;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=25 WHERE Id=11009;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=8614 WHERE Id=11067;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=11563;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11769;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=11968;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=22 WHERE Id=12520;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12690;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12780;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12781;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=13438;
UPDATE broadcast_text SET EmoteID1=71 WHERE Id=14079;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14412;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15129;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15472;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16227;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16232;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16234;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16271;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16275;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16278;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16280;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=16286;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16647;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10430 WHERE Id=16659;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10431 WHERE Id=16660;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10423 WHERE Id=16691;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=17117;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17338;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10533 WHERE Id=17641;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17652;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17785;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17786;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18163;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18349;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18366;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11112 WHERE Id=18662;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=5 WHERE Id=18711;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18913;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18972;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19055;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19115;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19264;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19392;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=19448;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19450;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19891;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11076 WHERE Id=19939;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11104 WHERE Id=20037;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11253 WHERE Id=20048;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20126;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20156;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20283;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20367;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20379;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20380;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20395;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20692;
UPDATE broadcast_text SET ChatTypeID=3 WHERE Id=20710;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20719;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20932;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21075;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=24008;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=24856;

UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=774;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5458;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=4 WHERE Id=12516;
UPDATE broadcast_text SET EmoteID1=71 WHERE Id=14078;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14405;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16231;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16238;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10424 WHERE Id=16692;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10534 WHERE Id=17642;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=5 WHERE Id=18713;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=19447;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=19659;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11077 WHERE Id=19940;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11113 WHERE Id=20029;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11105 WHERE Id=20038;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11254 WHERE Id=20049;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20369;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=24857;

UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=776;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=5459;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12521;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=14415;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16229;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16236;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10535 WHERE Id=17643;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=5 WHERE Id=18707;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=19445;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20370;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=24858;

UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=777;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1150;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3263;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4540;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4541;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5785 WHERE Id=6094;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5787 WHERE Id=6095;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5788 WHERE Id=6096;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5786 WHERE Id=6097;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=6546;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=9489;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=6 WHERE Id=12517;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17562;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10536 WHERE Id=17641;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18730;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=11078 WHERE Id=19941;
UPDATE broadcast_text SET ChatTypeID=3 WHERE Id=20710;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21441;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21443;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21444;

UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=772;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=2 WHERE Id=12514;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10537 WHERE Id=17642;

UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=776;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=22 WHERE Id=12520;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=10538 WHERE Id=17643;

UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=506;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2384;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2564;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=4392;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5825 WHERE Id=6187;
UPDATE broadcast_text SET SoundEntriesID1=5826 WHERE Id=6188;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5827 WHERE Id=6192;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=6425;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=6874;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12322;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12323;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12324;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=153 WHERE Id=13368;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18368;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18589;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18972;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19598;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=19675;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19736;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=19742;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=20298;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20925;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20926;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=20928;
UPDATE broadcast_text SET EmoteID1=16 WHERE Id=20929;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21074;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21365;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=24193;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=24206;

UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=741;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1150;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1191;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=1410;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2384;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=2553;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3074;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=3543;
UPDATE broadcast_text SET EmoteID1=3 WHERE Id=3988;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4516;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5828 WHERE Id=6189;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=5829 WHERE Id=6190;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=7570;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=8617;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=8736;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=10894;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16646;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16744;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16771;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16781;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=16843;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18325;
UPDATE broadcast_text SET ChatTypeID=2, EmoteID1=153 WHERE Id=18658;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=18929;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19397;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19415;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19467;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19599;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19831;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19832;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19833;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19834;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19835;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19836;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19837;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=1 WHERE Id=19839;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19840;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20101;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20837;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=20841;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=20927;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21260;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21352;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21364;

UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4483;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=4515;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=11929;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17105;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17106;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17107;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17108;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17109;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=17110;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=21077;

UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4438;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4439;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4440;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4441;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4442;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4443;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4444;
UPDATE broadcast_text SET ChatTypeID=4 WHERE Id=4445;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12590;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12591;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12592;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=12593;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13883;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13884;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13885;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=13886;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15157;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15158;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15159;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15160;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15161;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=15162;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15194;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15195;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=15196;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=15298;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=15299;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=15300;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=15301;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16453;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16454;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16455;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16456;
UPDATE broadcast_text SET EmoteID1=22 WHERE Id=16576;
UPDATE broadcast_text SET EmoteID1=22 WHERE Id=16577;
UPDATE broadcast_text SET EmoteID1=22 WHERE Id=16578;
UPDATE broadcast_text SET EmoteID1=22 WHERE Id=16579;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16611;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16612;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=16613;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18707;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18708;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18710;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=18713;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18878;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18879;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18880;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18881;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18882;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18883;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18884;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=18885;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19050;
UPDATE broadcast_text SET ChatTypeID=2 WHERE Id=19056;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=19378;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=19379;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=19380;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=19381;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=19382;
UPDATE broadcast_text SET EmoteID1=5 WHERE Id=19385;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19841;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19842;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19843;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19844;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19845;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=19857;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20258;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=20259;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21353;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21354;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21355;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21356;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21655;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21656;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21688;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21689;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21694;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21696;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21697;
UPDATE broadcast_text SET ChatTypeID=1 WHERE Id=21702;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21706;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21710;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21714;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21718;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21720;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21726;
UPDATE broadcast_text SET ChatTypeID=1, SoundEntriesID1=7274 WHERE Id=21733;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=22238;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=22239;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=22240;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=22241;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=22242;
UPDATE broadcast_text SET EmoteID1=1 WHERE Id=22243;
UPDATE broadcast_text SET EmoteID1=22 WHERE Id=23395;
UPDATE broadcast_text SET EmoteID1=22 WHERE Id=23396;
UPDATE broadcast_text SET EmoteID1=22 WHERE Id=23397;
UPDATE broadcast_text SET EmoteID1=15 WHERE Id=23398;
UPDATE broadcast_text SET EmoteID1=15 WHERE Id=23399;
UPDATE broadcast_text SET EmoteID1=15 WHERE Id=23400;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=15 WHERE Id=24185;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=15 WHERE Id=24186;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=15 WHERE Id=24187;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=15 WHERE Id=24188;
UPDATE broadcast_text SET ChatTypeID=1, EmoteID1=15 WHERE Id=24190;

DROP TABLE creature_ai_texts;


