-- Heroic creature_template should share normal template visibilityDistanceType
-- SELECT * FROM `creature_template` WHERE `HeroicEntry` != 0 AND `visibilityDistanceType` != 0;
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18058; -- Hellfire Watcher (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18432; -- Nazan (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18433; -- Omor the Unscarred (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18434; -- Vazruden (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18435; -- Vazruden the Herald (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18436; -- Watchkeeper Gargolmar (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18601; -- Broggok (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18607; -- Keli'dan the Breaker (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18620; -- Shadowmoon Channeler (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 18621; -- The Maker (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 19893; -- Mennu the Betrayer (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 19894; -- Quagmirran (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 19895; -- Rokmar the Crackler (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20168; -- Ghaz'an (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20169; -- Hungarfen (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20183; -- Swamplord Musel'ek (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20184; -- The Black Stalker (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20188; -- Underbog Lurker (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20190; -- Underbog Shambler (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20266; -- Nexus-Prince Shaffar (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20267; -- Pandemonius (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20268; -- Tavarok (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20299; -- Auchenai Monk (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20303; -- Avatar of the Martyred (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20306; -- Exarch Maladaar (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20307; -- Flying Raging Soul (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20318; -- Shirrak the Dead Watcher (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20319; -- Spirit of Exarch Maladaar (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20521; -- Captain Skarloc (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20531; -- Epoch Hunter (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20535; -- Lieutenant Drake (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20548; -- Thrall (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20568; -- Grand Warlock Nethekurse (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20569; -- Heathen Guard (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20575; -- Reaver Guard (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20578; -- Sharpshooter Guard (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20579; -- Shattered Hand Archer (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20581; -- Shattered Hand Blood Guard (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20592; -- Shattered Hand Scout (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20595; -- Shattered Hand Zealot (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20596; -- Warbringer O'mrogg (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20597; -- Warchief Kargath Bladefist (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20629; -- Hydromancer Thespia (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20630; -- Mekgineer Steamrigger (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20632; -- Steamrigger Mechanic (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20633; -- Warlord Kalithresh (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20636; -- Ambassador Hellmaw (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20637; -- Blackheart the Inciter (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20645; -- Cabal Ritualist (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20652; -- Fel Overseer (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20653; -- Grandmaster Vorpil (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20654; -- Invisible Target (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20656; -- Malicious Instructor (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20657; -- Murmur (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20663; -- Void Portal (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20690; -- Darkweaver Syth (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20706; -- Talon King Ikiss (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20737; -- Aeonus (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20738; -- Chrono Lord Deja (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20744; -- Rift Lord (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20745; -- Temporus (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20746; -- Time Keeper (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 20993; -- Blood Guard Porung (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21525; -- Gatewatcher Gyro-Kill (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21526; -- Gatewatcher Iron-Hand (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21533; -- Mechano-Lord Capacitus (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21537; -- Pathaleon the Calculator (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21551; -- Commander Sarannis (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21558; -- High Botanist Freywinn (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21559; -- Laj (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21581; -- Thorngrin the Tender (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21582; -- Warp Splinter (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21588; -- Blackwing Drakonaar (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21589; -- Blazing Trickster (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21590; -- Dalliah the Doomsayer (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21598; -- Gargantuan Abyssal (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21599; -- Harbinger Skyriss (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21600; -- Harbinger Skyriss (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21601; -- Harbinger Skyriss (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21602; -- Millhouse Manastorm (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21616; -- Sulfuron Magma-Thrower (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21617; -- Akkiris Lightning-Waker (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21618; -- Twilight Drakonaar (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21620; -- Unbound Void Zone (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21621; -- Unchained Doombringer (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21622; -- Warden Mellichar (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21624; -- Wrath-Scryer Soccothrates (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21626; -- Zereketh the Unbound (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21712; -- Infinite Chrono-Lord (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21915; -- Coilfang Leper (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 21988; -- Avian Flyer (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 22129; -- Durnholde Lookout (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 22167; -- Infinite Timereaver (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 22170; -- Rift Keeper (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 22171; -- Rift Keeper (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 22172; -- Rift Lord (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 22300; -- Spore Strider (1)
UPDATE `creature_template` SET `visibilityDistanceType` = 3 WHERE `entry` = 22629; -- Lokholar the Ice Lord (1)

