-- Add trainer greetings for 661 trainers.

DROP TABLE IF EXISTS `trainer_greeting`;
CREATE TABLE `trainer_greeting` (
   `Entry` INT(11) UNSIGNED NOT NULL COMMENT 'Entry of Trainer',
   `Text` LONGTEXT COMMENT 'Text of the greeting',
   PRIMARY KEY(`Entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='Trainer system';

DROP TABLE IF EXISTS `locales_trainer_greeting`;
CREATE TABLE `locales_trainer_greeting` (
   `Entry` INT(11) UNSIGNED NOT NULL COMMENT 'Entry of Trainer',
   `Text_loc1` LONGTEXT COMMENT 'Text of the greeting locale 1',
   `Text_loc2` LONGTEXT COMMENT 'Text of the greeting locale 2',
   `Text_loc3` LONGTEXT COMMENT 'Text of the greeting locale 3',
   `Text_loc4` LONGTEXT COMMENT 'Text of the greeting locale 4',
   `Text_loc5` LONGTEXT COMMENT 'Text of the greeting locale 5',
   `Text_loc6` LONGTEXT COMMENT 'Text of the greeting locale 6',
   `Text_loc7` LONGTEXT COMMENT 'Text of the greeting locale 7',
   `Text_loc8` LONGTEXT COMMENT 'Text of the greeting locale 8',
   PRIMARY KEY(`Entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='Trainer system';

INSERT INTO `trainer_greeting` VALUES (198, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (328, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (331, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (375, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (376, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (377, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (459, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (460, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (461, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (514, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (543, '');
INSERT INTO `trainer_greeting` VALUES (812, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (837, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (895, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (906, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (908, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (911, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (912, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (913, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (914, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (915, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (916, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (917, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (918, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (925, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (926, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (927, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (928, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (944, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (985, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (986, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (987, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (988, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1103, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (1215, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (1218, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (1226, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1228, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1229, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1231, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1232, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1234, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1241, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (1292, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (1300, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (1317, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (1346, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (1355, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (1382, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (1385, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (1386, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (1404, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1411, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (1430, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (1458, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (1470, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (1473, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (1632, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (1651, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (1676, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (1680, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (1681, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (1683, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (1699, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (1700, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (1701, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (1702, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (1703, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (1901, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2114, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (2119, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2122, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2123, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2124, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2126, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2127, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2128, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2129, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2130, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2131, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (2132, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (2326, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (2327, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (2329, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (2367, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (2390, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (2391, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (2399, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (2485, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (2489, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (2492, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (2627, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (2704, '');
INSERT INTO `trainer_greeting` VALUES (2798, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (2818, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (2834, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (2836, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (2837, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (2855, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (2856, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (2878, '');
INSERT INTO `trainer_greeting` VALUES (2879, '');
INSERT INTO `trainer_greeting` VALUES (2998, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (3001, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (3004, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (3007, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (3009, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (3011, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (3013, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (3026, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (3028, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (3030, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3031, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3032, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3033, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3034, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3036, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3038, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3039, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3040, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3041, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3042, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3043, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3044, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3045, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3046, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3047, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3048, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3049, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3059, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3060, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3061, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3062, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3063, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3064, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3065, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3066, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3067, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (3069, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (3087, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (3136, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (3137, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (3153, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3154, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3155, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3156, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3157, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3169, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3170, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3171, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3172, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3173, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3174, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (3175, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (3179, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (3181, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (3184, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (3185, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (3290, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (3306, '');
INSERT INTO `trainer_greeting` VALUES (3324, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3325, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3326, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3327, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3328, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3332, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (3344, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3345, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (3347, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (3352, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3353, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3354, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3355, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (3357, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (3363, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (3365, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (3373, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (3399, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (3401, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3403, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3404, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (3406, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3407, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3408, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3478, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (3484, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (3494, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (3523, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (3545, '');
INSERT INTO `trainer_greeting` VALUES (3549, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (3555, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (3557, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (3593, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3594, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3595, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3596, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3597, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3598, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3599, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3600, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3601, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3602, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3603, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (3604, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (3605, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (3606, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (3607, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (3620, '');
INSERT INTO `trainer_greeting` VALUES (3622, '');
INSERT INTO `trainer_greeting` VALUES (3624, '');
INSERT INTO `trainer_greeting` VALUES (3688, '');
INSERT INTO `trainer_greeting` VALUES (3690, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (3698, '');
INSERT INTO `trainer_greeting` VALUES (3703, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (3704, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (3706, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3707, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3963, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (3964, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (3965, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (3967, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (4087, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4089, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4090, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4091, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4092, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4138, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4146, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4156, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (4159, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (4160, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (4163, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4165, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (4193, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (4204, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (4205, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4210, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (4211, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (4212, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (4213, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (4214, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4215, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4217, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4218, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4219, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4254, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (4258, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (4320, '');
INSERT INTO `trainer_greeting` VALUES (4552, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (4563, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4564, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4565, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4566, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4567, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4568, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4573, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (4576, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (4578, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (4582, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4583, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4584, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4588, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (4591, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (4593, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4594, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4595, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4596, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (4598, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (4606, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4607, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4608, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (4611, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (4614, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (4616, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (4732, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (4752, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (4753, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (4772, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (4773, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (4898, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (4900, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (5032, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (5037, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (5038, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (5040, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (5041, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (5113, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5114, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5115, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5116, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5117, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5127, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (5137, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (5141, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5142, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5143, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5144, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5145, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5146, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5147, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5148, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5149, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5150, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (5153, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (5157, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (5159, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (5161, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (5164, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (5165, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5166, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5167, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5171, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5172, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5173, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5174, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (5177, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (5392, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (5479, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5480, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5482, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (5484, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5489, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5491, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5492, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5493, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (5495, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5496, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5497, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5498, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5499, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (5501, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5502, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (5504, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5505, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5506, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5511, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (5513, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (5515, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5516, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5517, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5518, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (5564, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (5566, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (5612, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5690, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (5695, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (5759, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (5784, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (5880, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5882, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5883, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5884, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5885, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (5938, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (5939, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (5941, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (5943, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (5957, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (5958, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (5994, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (6014, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (6018, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (6094, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (6251, 'Hello, warlock!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (6286, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (6287, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6288, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6289, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6290, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6291, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6292, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6295, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6297, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (6299, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (6306, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6387, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (6707, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (7087, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (7088, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (7089, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (7230, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (7231, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (7232, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (7311, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (7312, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (7315, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (7406, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (7866, 'Greetings! Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (7867, 'Greetings! Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (7868, 'Greetings! Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (7869, 'Greetings! Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (7870, 'Greetings! Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (7871, 'Greetings! Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (7944, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (7946, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (7948, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (7949, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (7953, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (7954, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (8126, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (8128, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (8140, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (8141, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (8142, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (8144, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (8146, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (8153, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (8306, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (8308, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (8736, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (8738, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (9465, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (9584, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (10086, '');
INSERT INTO `trainer_greeting` VALUES (10088, '');
INSERT INTO `trainer_greeting` VALUES (10089, '');
INSERT INTO `trainer_greeting` VALUES (10090, '');
INSERT INTO `trainer_greeting` VALUES (10930, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (10993, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (11017, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (11025, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (11031, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (11037, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (11048, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (11050, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (11051, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (11052, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (11072, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (11073, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (11074, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (11097, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (11098, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (11146, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (11177, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (11178, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (11397, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (11401, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (11406, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (11557, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (11865, '');
INSERT INTO `trainer_greeting` VALUES (11866, '');
INSERT INTO `trainer_greeting` VALUES (11867, '');
INSERT INTO `trainer_greeting` VALUES (11868, '');
INSERT INTO `trainer_greeting` VALUES (11869, '');
INSERT INTO `trainer_greeting` VALUES (11870, '');
INSERT INTO `trainer_greeting` VALUES (12025, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (12030, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (12032, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (12042, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (12961, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (13084, '');
INSERT INTO `trainer_greeting` VALUES (13283, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (13417, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (14740, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (15279, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (15280, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (15283, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (15284, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (15285, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (15400, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (15501, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (15513, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16000, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (16160, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (16161, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (16190, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (16253, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (16265, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (16266, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16269, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16270, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16271, '');
INSERT INTO `trainer_greeting` VALUES (16272, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (16273, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (16275, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16276, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16277, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (16278, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (16279, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16280, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (16366, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (16367, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (16499, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16500, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16501, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16502, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16503, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16583, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (16588, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (16621, '');
INSERT INTO `trainer_greeting` VALUES (16633, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (16639, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (16640, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (16642, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (16644, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (16646, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16647, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16648, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16651, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16652, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16653, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16654, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (16655, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16658, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16659, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16660, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16662, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (16663, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (16667, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (16669, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (16672, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16673, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16674, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16675, '');
INSERT INTO `trainer_greeting` VALUES (16676, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (16679, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16680, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16681, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16684, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16685, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16686, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16688, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (16692, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (16702, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (16712, '');
INSERT INTO `trainer_greeting` VALUES (16719, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (16721, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16723, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (16724, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (16725, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (16726, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (16727, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (16728, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (16729, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (16731, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (16736, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (16738, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16744, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (16746, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (16749, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16752, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (16755, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (16756, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16761, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16763, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (16771, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (16773, '');
INSERT INTO `trainer_greeting` VALUES (16774, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (16780, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (16823, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (17005, '');
INSERT INTO `trainer_greeting` VALUES (17089, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17101, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (17110, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17120, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17121, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17122, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17204, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17212, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17214, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (17215, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (17219, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17222, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (17245, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (17246, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (17424, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (17434, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (17441, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (17442, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (17480, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17481, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17482, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17483, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17484, '');
INSERT INTO `trainer_greeting` VALUES (17487, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (17488, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (17504, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17505, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17509, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17510, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17511, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17513, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17514, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17519, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17520, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17634, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (17637, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (17844, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (17983, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (18018, 'I can teach you how to use a fishing pole to catch fish.');
INSERT INTO `trainer_greeting` VALUES (18747, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (18748, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (18749, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (18751, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (18752, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (18753, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (18754, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (18755, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (18771, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (18772, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?');
INSERT INTO `trainer_greeting` VALUES (18773, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (18774, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (18775, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (18776, 'Searching for herbs requires both knowledge and instinct.');
INSERT INTO `trainer_greeting` VALUES (18777, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (18779, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (18802, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (18804, 'You have not lived until you have dug deep into the earth.');
INSERT INTO `trainer_greeting` VALUES (18987, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (18988, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (18990, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (18991, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (18993, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (19052, 'With alchemy you can turn found herbs into healing and other types of potions.');
INSERT INTO `trainer_greeting` VALUES (19063, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (19180, 'It requires a steady hand to remove the leather from a slain beast.');
INSERT INTO `trainer_greeting` VALUES (19184, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (19185, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (19186, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (19187, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (19251, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (19252, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (19340, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (19341, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (19369, 'Can I teach you how to turn the meat you find on beasts into a feast?');
INSERT INTO `trainer_greeting` VALUES (19478, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (19539, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (19540, 'Enchanting is the art of improving existing items through magic. ');
INSERT INTO `trainer_greeting` VALUES (19576, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (19774, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (19775, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (19777, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (19778, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?');
INSERT INTO `trainer_greeting` VALUES (20124, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (20125, 'Care to learn how to turn the ore that you find into weapons and metal armor?');
INSERT INTO `trainer_greeting` VALUES (20406, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (20407, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (20500, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (20511, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (20791, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (20914, 'Hello!  Can I teach you something?');
INSERT INTO `trainer_greeting` VALUES (21087, 'Greetings!  Can I teach you how to turn beast hides into armor?');
INSERT INTO `trainer_greeting` VALUES (22477, 'Here, let me show you how to bind those wounds....');
INSERT INTO `trainer_greeting` VALUES (23103, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (23127, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (23128, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (23534, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (24868, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (25099, 'Engineering is very simple once you grasp the basics.');
INSERT INTO `trainer_greeting` VALUES (26324, 'Hello, druid!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26325, 'Hello, hunter!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26326, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26327, 'Hello, paladin!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26328, 'Hello, priest!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26329, 'Hello, rogue!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26330, 'Hello, shaman!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26331, 'Hello, warlock! Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (26332, 'Hello, warrior!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (27703, 'Welcome!');
INSERT INTO `trainer_greeting` VALUES (27704, 'Hello, mage!  Ready for some training?');
INSERT INTO `trainer_greeting` VALUES (27705, 'Welcome!');
